### ISSUE TITLE
问题：我想一直使用fullscreen模式,而且按esc也不会退出

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#100]
我想一直使用全屏模式，即使按ESC也不会退出全屏，我要怎么做？

**Comment by pandao** [comment]
@wakaryry 高度和宽度都设为 100% 。

**Comment by wakaryry** [comment]
@pandao 我想清除当前屏，不知道有没有直接清除的方法。别人点击新建文本的时候，不想重新加载，想直接清除当前屏，然后插入一些初始值。

**Comment by pandao** [comment]
@wakaryry 

```javascript
editor.clear();
```
