### ISSUE TITLE
> * 会隔行出现斜体,被解释成了 * xx * ？

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#101]
如图所示：
![12345](https://cloud.githubusercontent.com/assets/7576559/7983523/bce8a3ea-0af3-11e5-88e4-c1ef9d197978.png)

**Comment by pandao** [comment]
@wakaryry `<blockquote>` 引用的 CSS 样式默认是斜体的。

**Comment by wakaryry** [comment]
但是我修改掉了的。我将其改成了normal。
```
> - jjjj
> - ggg
```
这样的话显示正常。

**Comment by wakaryry** [comment]
@pandao 
![rrrrrrr](https://cloud.githubusercontent.com/assets/7576559/8005578/426183f0-0bbe-11e5-9d7c-401979cf2ab8.png)

**Comment by pandao** [comment]
@wakaryry 好像是每隔一行就是斜体，一行正常。
