### ISSUE TITLE
想修改全屏预览时的位置和大小

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#103]
全屏预览时，默认显示是width:100%;padding:20px。

但是这样显示看上去并不舒服。我想全屏预览应该要比编辑器下实时预览更要灵活得多。因为更 想看到的是文章发布后的效果，这样的话显示的位置以及占用的宽度就显得很重要了。而只是纯粹的将实时预览的放到整个屏幕不符合要求。

建议点击全屏预览之后，增加一个与实时预览不相关的class，这样的话就可以自定义那个class，然后控制显示位置和大小了。

实际图：
![ddfff](https://cloud.githubusercontent.com/assets/7576559/8005319/514665e6-0bbb-11e5-8457-ebbfcc12db47.png)

效果图：
![hhhhh](https://cloud.githubusercontent.com/assets/7576559/8005327/766e97bc-0bbb-11e5-99f8-3c40d6638540.png)

**Comment by pandao** [comment]
@wakaryry 嗯，可以考虑。

**Comment by wakaryry** [comment]
我问题有点多：
我想获得所有的H标题，并且可以用于外部HTML中。然后点击某级标题直接滑动到那里。不知道怎么获取。

还有想问一下有没有字数统计。

@pandao 
谢谢

**Comment by pandao** [comment]
@wakaryry 可以自定义 TOC 菜单的容器元素，参考示例 [https://pandao.github.io/editor.md/examples/toc.html](https://pandao.github.io/editor.md/examples/toc.html)。

不知道 CodeMirror 有没有字数统计的方法，不然就得自己实现了。

**Comment by wakaryry** [comment]
@pandao 
是可以显示出来。不过有点小瑕疵。比如我粘贴一篇文章到编辑器里面，然后马上点击获取目录章节，结果获取到空值。而当我在任何一个地方编辑一下内容，再点击获取目录章节，这样就可以正常显示出来。

不知道什么情况。你给的那个例子也有这种情况：当你修改了内容时，点击获取TOC，结果没显示，而当再输入内容时就会显示出TOC。

**Comment by wakaryry** [comment]
@pandao 
还有就是我想在非编辑状态下获取TOC，作为别人阅读的导航。

**Comment by pandao** [comment]
@wakaryry 没听明白，不过试了一下，自定义 TOC 容器还有改进的空间。另外，非编辑状态下获取TOC只是等新版本更新了。

**Comment by wakaryry** [comment]
想了想，觉得非编辑状态下获取也没啥用。一般想要的话可能自己写更加合适些。

**Comment by pandao** [comment]
@wakaryry v1.5.0 支持非编辑状态下的自定义 ToC 容器。

**Comment by wakaryry** [comment]
@pandao 
看了下更新日志。感觉很好。
谢谢。
希望越来越漂亮。
