### ISSUE TITLE
htmlDecode: 代码中<script>XXX</script>内容解释出错

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#105]
``` javascript
<script type="text/javascript" src="http://lib.sinaapp.com/js/jquery/1.9.0/jquery.min.js"></script>
```
在编辑中被屏蔽掉了

![123](https://cloud.githubusercontent.com/assets/7576559/8023127/c0e95240-0d2e-11e5-8d30-e69f1138b032.png)

**Comment by pandao** [comment]
@wakaryry 嗯，先标记一下，稍后一并修正，被之前的改动影响到了。

**Comment by wakaryry** [comment]
@paodao

还有<style></style>

**Comment by pandao** [comment]
@wakaryry v1.5.0 fixed.
