### ISSUE TITLE
图片上传弹出框显示问题

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#106]
当窗口变小时，图片上传弹出框出现问题：
![uploadimage](https://cloud.githubusercontent.com/assets/7576559/8024386/190d1fee-0d64-11e5-9873-a64c1cfc202a.png)

**Comment by pandao** [comment]
@wakaryry 没有发现这样的问题，你自己检查一下吧。

**Comment by wakaryry** [comment]
@pandao 
好的。

**Comment by wakaryry** [comment]
![imageerror](https://cloud.githubusercontent.com/assets/7576559/8049280/c665dec0-0e8f-11e5-8b33-45bf1bea1f62.png)
我360浏览器和火狐浏览器打开都是这样的。

**Comment by pandao** [comment]
@wakaryry 看了一下，这是主页的兼容问题，不是 Editor.md 本身的问题。
