### ISSUE TITLE
初始化后右侧预览区出现了关闭按钮

### ISSUE THREAD

**Issue by lenbo-ma** [pandao/editor.md#11]
初始化代码为:
```
var editor = editormd("note-detail", {
     path: 'lib/editormd/lib/'
});
```

右侧实时预览区出现了关闭按钮，  触发editor.previewing();  再点击关闭按钮就消失正常了。

**Comment by pandao** [comment]
＠lenbo-ma 这应该在你提交的pull request中得到解决了吧？我已经合并你的pull request。

**Comment by lenbo-ma** [comment]
没有， 我那个是解决了无法获取预览窗口的HTML源码的问题

**Comment by pandao** [comment]
嗯，我大概知道什么问题了。

**Comment by lenbo-ma** [comment]
这个问题现在是否解决了？

**Comment by pandao** [comment]
你是不是又在onload之前调用了？

**Comment by lenbo-ma** [comment]
我一直都没有在onload之前调用什么函数

**Comment by lenbo-ma** [comment]
```
markdownEditor = editormd("note-detail", {
//          watch: false,
          lineNumbers: false,
          toolbar: false,
          tex : true,   // 开启科学公式TeX语言支持，默认关闭
          flowChart : true, // 开启流程图支持，默认关闭
          sequenceDiagram : true, // 开启时序/序列图支持，默认关闭,
          path: 'lib/editormd/lib/'
      });
```
这是我的配置

**Comment by pandao** [comment]
其他代码也贴出来吧

**Comment by lenbo-ma** [comment]
就这么多。 note-detail是一个div，markdown未初始化前，textarea中有值

2015-02-19 16:47 GMT+08:00 pandao <notifications@github.com>:

**Comment by pandao** [comment]
你是怎么触发editor.previewing(); ？

**Comment by lenbo-ma** [comment]
http://md.mlongbo.com/   右上角有一个预览按钮，点击按钮时调用了 editor.previewing();

**Comment by pandao** [comment]
出现关闭按钮是Editor.md自带的交互功能，你完全可以自己修改，例如隐藏它。

**Comment by lenbo-ma** [comment]
我已经改掉了。我觉得这是一个bug，所以就提了出来

2015-02-19 17:07 GMT+08:00 pandao <notifications@github.com>:

**Comment by pandao** [comment]
我不认为这是，最初设计的应用场景不是像你那种在线Markdown文档编辑服务http://md.mlongbo.com/ ，所以我才加上一个关闭按钮。

**Comment by lenbo-ma** [comment]
我想你没明白我的意思  我所说的bug是第一张图中出现的关闭按钮，这个按钮被点击了之后没有任何反应(这个没有意义，这个bug在你的官方示例中是没有看到的).而你所说的应用场景应该是第二张图(ps:  这个设计确实很好)。

![2015-02-19 17 13 00](https://cloud.githubusercontent.com/assets/2613341/6264046/9b47a1b4-b85a-11e4-8a80-cf4d6741cbc9.png)

![2015-02-19 17 13 55](https://cloud.githubusercontent.com/assets/2613341/6264057/b6020350-b85a-11e4-9456-317772b471e9.png)

**Comment by pandao** [comment]
像你这种应用场景你直接用只读模式不是更好？http://md.mlongbo.com/doc.html，previewing方法是应用在全编辑器窗口预览HTML。

**Comment by lenbo-ma** [comment]
嗯，谢谢提醒。我改一下[?]

2015-02-19 17:23 GMT+08:00 pandao <notifications@github.com>:

**Comment by pandao** [comment]
嗯，感觉你说不清楚，我也没听明白，急得我都快"抓狂"了。-_-!!

**Comment by ruanjiayou** [comment]
这个应该设个配置项的。
只能这样了
.editormd-preview-close-btn { display: none; }

**Comment by DDDDh** [comment]
@ruanjiayou 请问你是怎么改的？
