### ISSUE TITLE
TOCM 体验有点糟糕

### ISSUE THREAD

**Issue by xream** [pandao/editor.md#110]
![2015-06-10 07 46 06](https://cloud.githubusercontent.com/assets/1210282/8072165/e869c738-0f44-11e5-8751-81259e546121.png)

如果层级再多一点就完全乱套了...

**Comment by pandao** [comment]
@xream 那该如何做才能体验好点？

**Comment by xream** [comment]
@pandao 我觉得出现层级过多的时候可能本来就不适合用 TOCM 了...浮动体验不行可以试试展开...
Bootstrap 中的 Affix 感觉不错
比如项目中的这个页面 https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html-custom-toc-container.html
其实右侧的 TOC 换成 Bootstrap 右侧那种形式更好 http://getbootstrap.com/javascript/#affix

**Comment by pandao** [comment]
@xream 受限于编辑器宽度（有些场景下默认不是全屏的），不然另设一个侧边栏来存放全部展开的 ToC 菜单会比较好点。

**Comment by PaniniGelato** [comment]
我是干脆用JS抓整个TOC的html，在侧边重新生成一个菜单，原来的隐藏掉…
