### ISSUE TITLE
希望增加类似StackEdit的样式

### ISSUE THREAD

**Issue by ribber** [pandao/editor.md#114]
最近一直在使用您的Markdown编译器，感觉非常好用，非常感谢。但是最近用的时候总是感觉眼睛很累。自己试着改您的样式改的很乱。试用StackEdit感觉样式很舒服，眼睛也不是很累。希望您可以增加类似的主题。

**Comment by pandao** [comment]
@ribber 有空的话，可以考虑一下。不过还是鼓励大家自己去自定义主题，不可能一一满足每个人的独特需求。

**Comment by ribber** [comment]
@pandao 我研究了一下，已经自己自定义了样式，感谢
