### ISSUE TITLE
建议增加通过样式类选择markdown

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#118]
可不可以通过class来选择渲染的markdown（转换成HTML）或者允许同名ID值。
这样的话就不需要一个个去 写了。
比如将这个markdown编辑器作为评论输入框，像github这样，我该如何渲染(markdowntohtml)别人每次评论的内容。每次增加一个editorview实例？

**Comment by wakaryry** [comment]
我算是知道了，不显示是与上面的一起作为了<h1>了。我定义的<h1>没有下划线。

可是为什么我的一出现`XXX`然后下面的横线就无法识别了。

**Comment by wakaryry** [comment]
还有个问题：
可不可以通过class来选择渲染的markdown（转换成HTML）或者允许同名ID值。
这样的话就不需要一个个去 写了。
比如将这个markdown编辑器作为评论输入框，像github这样，我该如何渲染(markdowntohtml)别人每次评论的内容。每次增加一个editorview实例？

**Comment by pandao** [comment]
@wakaryry 没有通过样式类来渲染 Markdown 的功能，之前没考虑到，先标记一下，下个版本改进。

**Comment by wakaryry** [comment]
好期待下一个版本更新。
谢谢
