### ISSUE TITLE
编辑好了。有没有可以直接上传到服务器的

### ISSUE THREAD

**Issue by guoxiangwen** [pandao/editor.md#121]
编辑好了。有没有可以直接上传到服务器的。可自动生成目录树！

**Comment by wakaryry** [comment]
？
自动提交

**Comment by pandao** [comment]
@guoxiangwen 这只是一个编辑器，后台部分需要用户自己实现。你可以直接将解析后的 HTML 保存到数据库。

**Comment by L-xm** [comment]
@pandao 后台得到了HTML，那么应该添加哪些CSS文件到HTML文件中

**Comment by pandao** [comment]
@L-xm 请参考示例：[https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html) 

```html
<link rel="stylesheet" href="css/editormd.preview.css" />

<script src="js/jquery.min.js"></script>
<script src="../lib/marked.min.js"></script>

<!-- 开启代码高亮时 start -->
<script src="../lib/prettify.min.js"></script>

<!-- 开启流程图和时序图时 start -->
<script src="../lib/raphael.min.js"></script>
<script src="../lib/underscore.min.js"></script>
<script src="../lib/sequence-diagram.min.js"></script>
<script src="../lib/flowchart.min.js"></script>
<script src="../lib/jquery.flowchart.min.js"></script>
<!-- 开启流程图和时序图时 end -->

<script src="../editormd.js"></script>
```

**Comment by L-xm** [comment]
@pandao 忘记回复了，sorry。我通过mdEditor.getPreviewedHTML()函数获得预览HTML，用一个这样的div标签`<div class="markdown-body editormd-preview-container editormd-preview-active" previewcontainer="true">[mdEditor.getPreviewedHTML()]</div>`包裹它,然后引入在`head`引入`<link rel="stylesheet" href="css/editormd.preview.css" />`就可以正常渲染了。

**Comment by zhenqicai** [comment]
@pandao 你好 我也弄了个java 上传图片 图片却上传到服务器上了 但没有返回 图片地址给editor.md界面？ 图片上传成功需要返回 json数据给editor.md界面 {"success":1, "message":"上传成功","url":"http://localhost:8080/ssm/upload/155014.png"} ，测试都在本地，应该同域吧！图片上传到服务端了，服务端返回的json数据也对啊！但editor.md界面还是没有得到图片？

**Comment by wakaryry** [comment]
@zhenqicai 如果图片地址有返回的画，还是建议你查看下图片的地址是否正确。看HTML代码中的图片地址是否真的是你期望的那个。

**Comment by zZ-GitHub** [comment]
f12 看看就行了
