### ISSUE TITLE
Python博客项目中使用了editor.md，图片上传中遇到因xsrf问题而无法进行图片上传。

### ISSUE THREAD

**Issue by iter00** [pandao/editor.md#132]
项目使用Python+Tornado框架。
Tornado框架开启了XSRF防范机制，因此需要上传时同时传递XSRF到后端。请教这个要如何处理？
非常感谢！

**Comment by pandao** [comment]
@iter00 对 Python 和 Tornado 不了解，所以不能帮到你了。

**Comment by wakaryry** [comment]
python Django亲测可以使用

**Comment by iter00** [comment]
@pandao 我需要修改一些，POST提交的時候多提交一個項目就可以了，麻煩不吝指導，非常感謝！

**Comment by iter00** [comment]
@wakaryry CSRF怎麼處理？

**Comment by iter00** [comment]
@pandao 问题已解决，不用麻烦了，感谢！

**Comment by byteli** [comment]
@iter00 请问你是怎么解决的，在imageUploadUR里加的么么？
