### ISSUE TITLE
建议添加字符统计功能

### ISSUE THREAD

**Issue by greycode** [pandao/editor.md#133]
加个实时字符统计还是挺实用的，尤其在需要限制字符数的场景下

**Comment by pandao** [comment]
@greycode 嗯，可以考虑一下，之前也有同学有提过。

**Comment by wakaryry** [comment]
我每天都来看看是否已经更新。最近作者可能太忙了。好长时间没有更新了。

**Comment by zhangruinian** [comment]
> 我每天都来看看是否已经更新。最近作者可能太忙了。好长时间没有更新了。

三年都过去了, 三年之后又三年 还是没更新
