### ISSUE TITLE
怎么取原编辑的 html 和预览的html？

### ISSUE THREAD

**Issue by a610569731** [pandao/editor.md#135]
怎么取原编辑的 html 和预览的html？

**Comment by qinyuanpei** [comment]
我采用了这样一种方式来生成一个新的HTML页面：

![qq 20151023153809](https://cloud.githubusercontent.com/assets/7688258/10687057/bbc74dd2-799c-11e5-8855-2109c3ee25ec.png)

其中htmlOfEditor的值等于editor.getHTML()，所以这样大概可以实现你的需求，但是这里有个问题啊，我生成的HTML页面是有滚动条的，我参考是[https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html)，但是不知道为什么会是这样的结果，这让我郁闷啊！

**Comment by pandao** [comment]
* 编辑模式下，可以用 `getHTML()` 或者 `getPreviewedHTML()` 方法获取；
* 非编辑模式下，显示 HTML，详见：https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html
