### ISSUE TITLE
全窗口预览情况下，拉动浏览器窗口宽度，布局变了

### ISSUE THREAD

**Issue by lenbo-ma** [pandao/editor.md#14]
第一张图是点击“全窗口预览HTML(可按ESC还原)" 按钮后的正常视图。

第二张图是我拉动浏览器窗口边缘改变后出现的视图。

不知道描述的是否明确?  

在这里测试的   https://pandao.github.io/editor.md/

![default](https://cloud.githubusercontent.com/assets/2613341/6264452/2586a1e6-b85f-11e4-8c82-fd67a04a5e1b.png)

![bug](https://cloud.githubusercontent.com/assets/2613341/6264456/2b8559d4-b85f-11e4-8a68-31e6d43f2f91.png)

**Comment by pandao** [comment]
嗯，先标记一下，过后一并处理。

**Comment by lenbo-ma** [comment]
哈哈，你可以说明下原因，我试试能不能改

**Comment by pandao** [comment]
@v1.1.3 fix
