### ISSUE TITLE
支持键盘快捷键

### ISSUE THREAD

**Issue by yan9yu** [pandao/editor.md#152]
希望后续可以支持 Vim/Emacs 模式进行编辑操作

**Comment by qinyuanpei** [comment]
KeyMap里可以自定义快捷键啊，自己去实现不就好了，接口都是现成的啊

**Comment by zhangyongqiang010** [comment]
苹果的command + s 怎么设置

**Comment by zhangyongqiang010** [comment]
苹果电脑command-s怎么设置

**Comment by zhangyongqiang010** [comment]
var keyMap = {
                "command-S": function(cm) { // default Ctrl-A selectAll
                    // custom
                    alert("Command-S");
                }
            };
            this.addKeyMap(keyMap);
