### ISSUE TITLE
请问如何在前台调用数据库存储好的markdown内容

### ISSUE THREAD

**Issue by ijry** [pandao/editor.md#153]
请问如何在前台调用数据库存储好的markdown内容

**Comment by nosqldb** [comment]
同问，如果markdown渲染在服务端端做的，就没有保存html，换用这个编辑器就有问题

**Comment by JiangRuyi** [comment]
> 这个符号被转义。。。。。

**Comment by wakaryry** [comment]
参考：https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html

**Comment by qinyuanpei** [comment]
调用setMarkdown方法就好啦，传入的参数是markdown书写的文件内容，如果里面有HTML代码的话，需要处理的

**Comment by pandao** [comment]
* 编辑模式下，通过配置项 `markdown` 或者调用 `setMarkdown()` 方法，设置 Markdown 内容；
* 非编辑模式下，Markdown 显示为 HTML，参考这个：https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html
