### ISSUE TITLE
如何清空编辑器内容

### ISSUE THREAD

**Issue by nishuer** [pandao/editor.md#160]

**Comment by pandao** [comment]
@hellonishu 可以使用 `clear()` 方法来清空编辑器，或者使用 `setValue("")` 方法。

**Comment by bestony** [comment]
`editor.clear()`或`document.getElementById('editormd').clear()` 都不可以，这个方法如何使用呢？

**Comment by xiamuguizhi** [comment]
@nishuer 
               $("#qk-btn").bind('click', function() {
                    testEditor.setValue("");
                });

**Comment by iloveuaa** [comment]
这个bug直到今天都没有解决

**Comment by twolao** [comment]
> ```js
> testEditor.clear()
> ```

TypeError: testEditor.clear is not a function

testEditor.hide is ok
