### ISSUE TITLE
表格预览没问题，发表后，文章表格就有问题

### ISSUE THREAD

**Issue by nosqldb** [pandao/editor.md#165]
```
| a  |  b | c  | d  |
| ------------ | ------------ | ------------ | ------------ |
|  1 |  2 | 3  | 4  |
```

| a | b | c | d |
| --- | --- | --- | --- |
| 1 | 2 | 3 | 4 |

**Comment by pandao** [comment]
@nosqldb 能否说的详细一点？

**Comment by nosqldb** [comment]
@pandao 预览是这样的：
![1](https://cloud.githubusercontent.com/assets/4327423/11033434/e8ddf54e-871d-11e5-9a37-039f6c2ddcd8.PNG)

发表后是这样的：
![2](https://cloud.githubusercontent.com/assets/4327423/11033439/f9ab3e18-871d-11e5-8fc5-71de5ce86bbf.PNG)

**Comment by pandao** [comment]
@nosqldb 预览的样式文件有引用对吗？

**Comment by nosqldb** [comment]
@pandao  貌似不少。
editormd.min.css
codemirror.min.css,dialog.css,matchesonscrollbar.css

**Comment by pandao** [comment]
@nosqldb 前台HTML显示参考示例：[https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html)

**Comment by hellonishu** [comment]
@nosqldb 引入editormd.min.css文件就可以了，然后在你显示编辑器内容的DIV上加上“markdown-body editormd-preview-container”这个两个class
