### ISSUE TITLE
工具栏无法正常显示

### ISSUE THREAD

**Issue by Lwxiang** [pandao/editor.md#167]
### 对于简单的前段嵌入，工具栏的显示一直是乱码。想请问一下如何解决。

![描述](http://ww3.sinaimg.cn/mw690/aebcf8f5gw1exw5gbwv6xj20tx05fwf3.jpg)

**Comment by pandao** [comment]
@Lwxiang 图标字体文件没有正确引用，检查一下。

**Comment by bluekingtest** [comment]
@pandao 需要预编译之类的操作吗。从git上下载的zip包，点开example里面任意html，工具栏都是这个样子的。
