### ISSUE TITLE
为知笔记扩展问题

### ISSUE THREAD

**Issue by Michael728** [pandao/editor.md#169]
这是你的一个教程，找到index.html文件，但是没找到这些配置属性啊？奇怪
新建.md笔记，选择Editor.md编辑器编辑。
配置方法
如果需要开启或关闭一些功能，那么打开index.html文件，修改以下配置项：
codeFold        : true,              // 代码折叠，默认关闭
tex             : true,              // 开启科学公式TeX语言支持，默认关闭
flowChart       : true,              // 开启流程图支持，默认关闭
sequenceDiagram : true,              // 开启时序/序列图支持，默认关闭
toc             : true,              // [TOC]自动生成目录，默认开启
tocm            : false,             // [TOCM]自动生成下拉菜单的目录，默认关闭
tocTitle        : "",                // 下拉菜单的目录的标题
tocDropdown     : false,             // [TOC]自动生成下拉菜单的目录，默认关闭
emoji           : false,             // Emoji表情，默认关闭
taskList        : false,             // Task lists，默认关闭
复制代码
保存，重新启动为知笔记即可。

**Comment by akof1314** [comment]
@Michael728 为知笔记的扩展不在这里进行提问
