### ISSUE TITLE
建议：提供浮动的目录

### ISSUE THREAD

**Issue by dongyg** [pandao/editor.md#179]
建在预览模式下，也就是作为HTML web页面显示时，支持浮动的目录，当浏览文章上，在窗口右侧提供一个浮动的目录（类似于百度百科浏览时右侧目录的那种效果）。对于较长的文章浏览，非常方便。

**Comment by pandao** [comment]
@dongyg 建议你自己实现这个需求，参考示例：http://editor.md.ipandao.com/examples/toc.html
