### ISSUE TITLE
图片上传的问题

### ISSUE THREAD

**Issue by star7th** [pandao/editor.md#184]
我集成到一个web程序里后，编辑器初始化正常，点击插入标题这些按钮可以用，但点击添加图片的时候，则提示“Uncaught TypeError: Cannot set property 'imageDialog' of undefined”。编辑器初始化的时候已经添加了配置“
      imageUpload : true,
      imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
      imageUploadURL : "ImgUpload",

不过错误依旧。这有可能是什么引起的？
![unnamed qq screenshot20151204115509](https://cloud.githubusercontent.com/assets/2200494/11581575/68b1c57a-9a7e-11e5-8315-f5953a3d268a.png)

**Comment by star7th** [comment]
初始化编辑器的代码是：

```
  editormd = editormd("editormd", {
      width   : "90%",
      height  : 1000,
      syncScrolling : "single",
      path    : DocConfig.pubile + "/editor.md/lib/" ,
      placeholder : "本编辑器支持Markdown编辑，左边编写，右边预览",
      imageUpload : true,
      imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
      imageUploadURL : "ImgUpload",

  });
```

**Comment by star7th** [comment]
这个问题有解了吗

**Comment by xyzget** [comment]
```
path    : DocConfig.`pubile` + "/editor.md/lib/" ,
```
你确定是publie?没有乒协错误？

**Comment by star7th** [comment]
DocConfig.pubile  这是我前文定义的一个对象。按理说它是没问题的，因为编辑器的确能初始化，只是某些按钮不能用。像插入一级二级标题这些倒能用

**Comment by fengjx** [comment]
我也碰到这个错误，解决没有呢？

**Comment by fengjx** [comment]
知道了，定义的editormd变量不能用”editormd“，与全局变量editormd冲突

**Comment by Ryongyon** [comment]
imageUploadURL : "ImgUpload"
这里这个ImgUpload是什么？不应该是“./php/upload.php”么？

**Comment by zhenqicai** [comment]
@star7th  你这个问题解决了吗？我也遇到类似的问题：
![90421](https://user-images.githubusercontent.com/20643420/33993670-7d6f504a-e112-11e7-8f6b-90428485da5e.png)

**Comment by star7th** [comment]
@zhenqicai 手动引入插件的js。应该是自动引入出错了所以要手动。

**Comment by Brian-liah** [comment]
你好，我也遇到相同问题：如何解决呢？？
![2w 2ji 6t6 phc_cqc7gx1i](https://user-images.githubusercontent.com/23378591/45201107-75795000-b2a6-11e8-96aa-b6356411e044.png)
