### ISSUE TITLE
editormd.css中editormd-logo.eot引入错误

### ISSUE THREAD

**Issue by pauky** [pandao/editor.md#186]
src: url(".../fonts/editormd-logo.eot?#iefix-5y8q6h")

表示上级目录那里写了三个点,webpack打包时会报错

**Comment by pandao** [comment]
@pauky  `./../` 或者 `../` 这样才是表示上级目录。

**Comment by pauky** [comment]
工程里这个css/editormd.css里存在这个src: url(".../fonts/editormd-logo.eot?#iefix-5y8q6h")引入错误

**Comment by pandao** [comment]
@pauky 不好意思，是我自己写错了，谢谢你的提醒。

**Comment by jaradc** [comment]
@pandao how come you never fixed this? I'm grateful that you created this package, but not grateful that you left this simple and obvious mistake in it which wastes hours of peoples' time solving - which it could all be avoided if you just pushed an update.

**Comment by qikai9** [comment]
npm ^1.5.0 版本依然有 ... 的书写错误,导致loader解析失败
