### ISSUE TITLE
图片上传成功后在前端的input中没有显示出图片的地址

### ISSUE THREAD

**Issue by lxue1986** [pandao/editor.md#189]
配置：
var testEditor = editormd("test-editormd", {
                path : 'js/editor.md/lib/',
                imageUpload : true,
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "u/upload-articlepic"
                
                /*
                                 上传的后台只需要返回一个 JSON 数据，结构如下：
                 {
                    success : 0 | 1,           // 0 表示上传失败，1 表示上传成功
                    message : "提示的信息，上传成功或上传失败及错误信息等。",
                    url     : "图片地址"        // 上传成功时才返回
                 }
                 */
	        });

后台返回的信息：{success:1,message:"上传成功",url:"avatar/UR1215159AH62FSS/1450238661731.jpg"}

但是在前端的窗口中图片的地址没有显示出来！

**Comment by lpx20000** [comment]
同样，我这边也遇到这个问题。看了下源代码，其实是没问题的，应该是你返回的写错了。

**Comment by phycholee** [comment]
我也有这个问题，还没解决，返回的json也没问题啊，怎么解决的？

**Comment by Ryongyon** [comment]
控制台有没有报错信息？
另外自荐一下自己做的七牛图片上传中间件：https://github.com/Ryongyon/QiniuImageUpload-for-Editor.md
