### ISSUE TITLE
关于在为知笔记中缩进的问题

### ISSUE THREAD

**Issue by pitpah** [pandao/editor.md#191]
### 背景
用windows版时，发现不能使用Tab缩进。
点Tab时，并没有效果...

### 诉求

能不能用TAB代替四个空格，强迫症看着比较舒服

**Comment by pitpah** [comment]
@pandao 求解决~

**Comment by zydxhs** [comment]
求解决~~~~~~~~~

**Comment by akof1314** [comment]
@zydxhs 为知笔记版的话，要用F1代替TAB缩进，因为TAB被为知拦截了。

**Comment by pitpah** [comment]
@akof1314  多谢指导，太感谢了~
