### ISSUE TITLE
请问在jave web程序中如何实现图片本地上传功能

### ISSUE THREAD

**Issue by Orange1991** [pandao/editor.md#196]
大大你好，我现在在做一个java web项目，看到您这个editor里的上传是php实现的，请问我该如何使用这个功能？

**Comment by pandao** [comment]
@Orange1991 用 Java 写上传程序，按格式返回 JSON 数据就可以了。

**Comment by zhenqicai** [comment]
@pandao 你好 我也弄了个java 上传图片 图片却上传到服务器上了， 但没有返回图片地址给editor.md界面？ 图片上传成功需要返回 json数据给editor.md界面 {"success":1, "message":"上传成功","url":"http://localhost:8080/ssm/upload/155014.png"}

**Comment by Orange1991** [comment]
@zhenqicai 我大概这么做的，参考吧：
```
// editor configuration
imageUploadURL : "<%=basePath%>editormd/jsp/upload.jsp",
uploadCallbackURL: "<%=basePath%>editormd/jsp/upload_callback.jsp",
```
[upload.jsp.txt](https://github.com/pandao/editor.md/files/1554066/upload.jsp.txt) 部分代码参考网络资料，仅供学习交流
[upload_callback.jsp.txt](https://github.com/pandao/editor.md/files/1554067/upload_callback.jsp.txt) 对editorme中的upload_callback.html有修改

当然你也可以把上传的那个写成action servlet。

**Comment by Orange1991** [comment]
@zhenqicai 我大概这么做的，参考吧：
```
// editor configuration
imageUploadURL : "<%=basePath%>editormd/jsp/upload.jsp",
uploadCallbackURL: "<%=basePath%>editormd/jsp/upload_callback.jsp",
```
[upload.jsp.txt](https://github.com/pandao/editor.md/files/1554066/upload.jsp.txt) 部分代码参考网络资料，仅供学习交流
[upload_callback.jsp.txt](https://github.com/pandao/editor.md/files/1554067/upload_callback.jsp.txt) 对editorme中的upload_callback.html有修改

当然你也可以把上传的那个写成action servlet。

**Comment by zhenqicai** [comment]
@Orange1991  上传有返回URL地址过来

**Comment by Orange1991** [comment]
@zhenqicai 上传完后返回url给editor的部分，仔细看upload.jsp那里的redirect的传参吧
