### ISSUE TITLE
希望添加页内跳转

### ISSUE THREAD

**Issue by zydxhs** [pandao/editor.md#197]
写文档时，经常需要链接到同一个文档的其它位置。

**Comment by zydxhs** [comment]
怎么没人理会？

**Comment by hawtim** [comment]
markdown语法好像是有实现锚点的方法，
http://blog.csdn.net/u010784236/article/details/44462903
如何使用： 
总之就是用于文章快速定位，点击目录便可直接跳转到指定位置。下面来介绍一下在MarkDown编辑器中怎么使用： 
首先是建立一个跳转的连接：
[说明文字](#jump)
1
1
然后标记要跳转到什么位置即可：
<span id = "jump">跳转到这里：</span>


如果是要生成目录树来实现跳转的话：可参考https://pandao.github.io/editor.md/examples/toc.html

**Comment by pandao** [comment]
@zydxhs 页内跳转可以使用锚点链接，另外目前不支持注脚。
