### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by zydxhs** [pandao/editor.md#198]
> df -h 　命令可以显示目前所有文件系统的可用空间及使用情形。
> du　　　递归摘要目录中每个文件的磁盘使用情况。
> du -sh　查看指定目录的磁盘占用大小。

上面的文字，右侧的中文描述怎么实现左对齐呢？
我尝试使用全角空格，还是无法对齐，原因是转换后的 html 字体不是等宽字体。
希望能够加上选项，设置转换后的 html 的字体。

**Comment by jasongwq** [comment]
建议使用表格

**Comment by pandao** [comment]
@zydxhs 可以使用代码块或者预格式文本，或者表格。
