### ISSUE TITLE
代码风格和目录风格太丑，可否提供自定义CSS？

### ISSUE THREAD

**Issue by aitanjupt** [pandao/editor.md#199]
代码风格和目录风格太丑，可否提供自定义CSS？

**Comment by pandao** [comment]
@aitanjupt 不知道你想要什么样的，这个需要你自己去自定义 CSS。

**Comment by HectorJiang** [comment]
> @aitanjupt 不知道你想要什么样的，这个需要你自己去自定义 CSS。

可以提供给自定义方法吗。

**Comment by Domingowen** [comment]
first 你们 提问的时候 可以温柔一点吗？直接就说丑 这谁也接受不了呀 你可以换成英文提问
second 这个是链接 [https://github.com/pandao/editor.md/issues/687#issuecomment-605048303](https://github.com/pandao/editor.md/issues/687#issuecomment-605048303)
