### ISSUE TITLE
使用KATEX替换MathJax

### ISSUE THREAD

**Issue by xiaobeicn** [pandao/editor.md#2]
https://github.com/Khan/KaTeX
http://khan.github.io/KaTeX/

**Comment by pandao** [comment]
谢谢推荐，可以考虑一下。目前的一个问题是MathJax在实时预览时，有重新加载的延迟问题。

**Comment by fifsky** [comment]
替换为国内的CDN地址试试 http://cdn.bootcss.com/mathjax/2.4.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

**Comment by pandao** [comment]
@fifsky MathJax地址可以自定义，你提供的这个URL我考虑添加到注释里，以供用户选择。
