### ISSUE TITLE
希望能给出选项可以使用Mathjax

### ISSUE THREAD

**Issue by riteme** [pandao/editor.md#206]
我个人是倾向与使用Mathjax的。虽然KATEX确实渲染很快，但功能不如Mathjax强大。
* KATEX不能使用`\tag`
* 渲染出的数学公式字体似乎太大了
* KATEX没有错误提示，只要数学公式有一点错误就完全不见了

如果可以的，希望能添加对Mathjax的支持，谢谢

**Comment by xaero7** [comment]
Mathjax迟早要被Katex超越的

**Comment by pandao** [comment]
@riteme 在最初的版本数学公式支持是基于 Mathjax 的，之后网友推荐了 Katex，比较之后发现 Katex 更好一点，所以后续版本就开始采用 Katex。如果你想用 Mathjax ，还是建议你动起手来改造属于你自已的 Editor.md 。

**Comment by riteme** [comment]
好的，我知道了
