### ISSUE TITLE
没有选中文本的情况下，某些按钮应该在行首插入

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#21]
输入 `文字` ， 将光标放在 `文` 和 `字` 之间, 点击 `h1` 按钮。

期望变成 `# 文字` ，实际上变成了 `文# 字` 。

这种行为跟流行的编辑器不一致，比如说Microsoft Word、TinyMCE、CKEditor等等。

有类似问题的按钮有 `引用`、`h1`、 `h2`、 `h3`、 `h4`、 `h5`、 `h6`、`无序列表`、`有序列表` 。

**Comment by pandao** [comment]
这个我就不认同了，谁会在两个字中间插入headers？

**Comment by tylerlong** [comment]
你可以做个实验， 打开 microsoft word (或者这里： http://ckeditor.com/demo)， 输入一行文字， 把光标放到文字中央，然后点击 h1

操作的含义就是 ｀把当前行变成h1｀， 而不是 ｀在当前位置插入h1｀。 这是为懒人准备的。 不必选中行，也不必把光标定位到行首。 

大部分编辑器都是这样的。 你想想看。

**Comment by pandao** [comment]
我觉得这样实在没有意义。
