### ISSUE TITLE
如何动态的设置editor的大小

### ISSUE THREAD

**Issue by Jiavan** [pandao/editor.md#212]
初始化完成后，不能更改editor的大小了吗，我想动态的改变它的大小，但是直接操作dom并没有预期的效果，像下面这样，有什么方法可以解决吗，比如传一个width，height就能更改
![qq 20160131103958](https://cloud.githubusercontent.com/assets/6786013/12699874/c180ede6-c807-11e5-9952-e31d0bb8141c.png)

thx :)

**Comment by pandao** [comment]
@Jiavan 动态改变尺寸的成员方法有：`width()`、`height()`、`resize(width, height)`。

**Comment by Jiavan** [comment]
问题解决，thx
