### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by inexuscore** [pandao/editor.md#215]
Just came across your repo. I've given this a try and I love this editor, awesome work.
Just curious about the **93 open issues** and the fact that its been 8+ months since last activities. Is this project dead?

**Comment by liuxianan** [comment]
haha, maybe.

**Comment by DeeJaVu** [comment]
yea its buggy and dead, if you know an alternative editor pls reply

**Comment by pandao** [comment]
No

**Comment by pandao** [comment]
统一回复：有空就会维护，不定期更新版本，请不要重复提问。
