### ISSUE TITLE
图片上传迫切希望

### ISSUE THREAD

**Issue by JeddyHj** [pandao/editor.md#219]
如果能够做图片直接粘贴复制就可以上传的功能是很快键和方便，实用性很高。例如ckeditor就做到这一点

**Comment by liniu** [comment]
确实需要这个功能，比如qq截图后可以粘贴上传就方便很多。

**Comment by pandao** [comment]
统一回复：图片粘贴上传功能有列入新版本特性中，请不要重复地提相同的 Issues。

**Comment by mifunc** [comment]
参照  https://rumenz.com/rumenbiji/editor-md-drag-upload-file.html
