### ISSUE TITLE
How to make the editor.md written document effect on github.com

### ISSUE THREAD

**Issue by MiniYun** [pandao/editor.md#22]
Visit here
Https://github.com/MiniYun/miniyun/blob/minidoc/docs/api/test.md
Part of the effect can not be presented.thanks

**Comment by pandao** [comment]
??

**Comment by MiniYun** [comment]
如何才能把editor.md上面写的内容在github.com上面生效。Https://github.com/MiniYun/miniyun/blob/minidoc/docs/api/test.md
这个页面上的流程图什么的，都无法显示。谢谢！

**Comment by tylerlong** [comment]
流程图之类的依赖于第三方的类库： flowchart.js  sequence-diagram.js

github.com 页面默认不会加载这些类库。 这个问题解决不了。

其实流程图之类的不是标准的markdown， github不支持也正常。

**Comment by pandao** [comment]
流程图和时序图部分是非标准的，属于第三方扩展，所以不能在Github显示。
