### ISSUE TITLE
能开发个react版的吗？

### ISSUE THREAD

**Issue by JerroldLee** [pandao/editor.md#226]
能开发个react版的吗？

**Comment by pandao** [comment]
不会开发 React 版

**Comment by Teddy-Zhu** [comment]
@pandao 其他mv* 框架的版本 ,有计划吗

**Comment by pandao** [comment]
@Teddy-Zhu 不会，大家自已动手吧~

**Comment by lizhengnacl** [comment]
[React Component Based on Editor.md](https://www.npmjs.com/package/wrap-md-editor)
