### ISSUE TITLE
HTML预览生成的dom元素id有重复

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#23]
以这个为例： https://pandao.github.io/editor.md/examples/full.html

![qq20150228-1](https://cloud.githubusercontent.com/assets/733544/6425763/4c950530-bf75-11e4-9238-4fe604648dd8.png)

id有很多"hello-world-". 

还有的id是"-".

**Comment by pandao** [comment]
这个我知道，基本上是中文无法转换或者同一标题内容的问题。

**Comment by pandao** [comment]
@v1.1.6 fixed.
