### ISSUE TITLE
调用 setMarkdown() 方法之后，代码没有语法高亮

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#24]
Chrome 浏览器访问 https://pandao.github.io/editor.md/examples/full.html

打开console， 执行: `testEditor.setMarkdown("\tfunction test() {\n\t\talert('test');\n\t}");`

HTML实时预览那里，代码没有语法高亮。

随便敲个回车空格之类的，触发onChange事件， 就有语法高亮了。

**Comment by pandao** [comment]
我这边试了可以呀

**Comment by tylerlong** [comment]
Mac OS X 10.10, Google Chrome Version 40.0.2214.115 (64-bit)

**Comment by tylerlong** [comment]
Win8 + Chrome 也测了，也不行

![image](https://cloud.githubusercontent.com/assets/733544/6437664/944ee0c0-c0fc-11e4-822b-0d97cd60128e.png)

有高亮的应该是这样：

![image](https://cloud.githubusercontent.com/assets/733544/6437682/b0259bb8-c0fc-11e4-9492-136d39653039.png)

**Comment by pandao** [comment]
嗯，试了一下，我这边Win7 + Chrome 39也不行，Change时没有及时加上代码高亮的样式类class="prettyprint linenums prettyprinted"。先标记一下，稍后一并修复。

**Comment by pandao** [comment]
@v1.1.6 fixed.

**Comment by thinkycx** [comment]
- 请问调用setMarkdown如何传入多行参数呢？
temp 中只要出现转义字符\r\n前端就会渲染失败。
请问是需要设置别的东西吗？
```javascript
    <script type="text/javascript">
        var temp = "{{ content }}";
        document.write(temp);
        $(function () {
            var testEditor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                saveHTMLToTextarea: true,
                path: "{{url_for('static', filename='editor.md/lib/')}}",
                htmlDecode : true ,
                onload: function(){
                // alert("onload");
                this.setMarkdown(temp);
                // console.log("onload =>", this, this.id, this.settings);
                 }
            });
        });
    </script>
```
