### ISSUE TITLE
如何导出markdown到html?

### ISSUE THREAD

**Issue by sunshe35** [pandao/editor.md#242]
这款编辑软件真心好用，我用的是为知笔记的editor.md插件，发现editor.md的渲染与为知笔记内部的渲染不同，而为知笔记导出文档用的是自己的渲染，因此我想通过editor.md自己的导出方法来导出HTML。
但是官网好像没有输出到html功能，所以我就不知道该如何做？

**Comment by pandao** [comment]
@sunshe35 保存为 HTML 文件需要后端配合，如果是获取编译后的 HTML 可以通过 `getPreviewedHTML()` 或 `getHTML()` 方法获取。

**Comment by sunshe35** [comment]
百度了一下，不知道你说的这两个方法怎么使用？这方面确实没有任何的经验。

**Comment by pandao** [comment]
@sunshe35 参考示例：http://editor.md.ipandao.com/examples/html-preview-markdown-to-html.html
