### ISSUE TITLE
建议开放编辑的原生事件还有粘贴事件

### ISSUE THREAD

**Issue by newpanjing** [pandao/editor.md#249]
现在上传图片只能够通过对话框来，但是很多的习惯是粘贴近来，然后自动上传~

**Comment by hawtim** [comment]
请问您在这一块的研究上有什么进展么？我遇到这个需求也在寻找解决方案

**Comment by newpanjing** [comment]
我也忘记了，后来换了其他解决方案。之前是把ueditor重写了的。

**Comment by pandao** [comment]
Duplicate of #219
