### ISSUE TITLE
onLoad 事件中调用 setMarkdown， Preview部分没有触发更新

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#25]
此问题在v1.1.5中没有发现，v1.1.6中发现的。

以这个为例子： https://pandao.github.io/editor.md/examples/onload.html

注释掉原来的onLoad代码，添加一行setMarkdown调用，最终代码如下：

```javascript
onload : function() {
    //alert("onload");
    //console.log("onload =>", this, this.id, this.settings);
    testEditor.setMarkdown("test onload");
}
```

载入页面之后，发现左侧的markdown内容已经变成了“test onload”， 但是右侧的预览并没有跟上。

只有在onLoad事件中调用setMarkdown才能重现这个问题。 之后再调用setMarkdown都是没问题的。

我猜测原因可能是： onLoad事件中，其实整个editor还没有彻底准备好，这时候调用它的某些方法会工作不正常。

建议解决方案： 等editor一切都ready之后再触发onLoad事件。 或者增加一个新的onReady事件。

**Comment by pandao** [comment]
老问题了，在Editor.md还没完全load之前不能直接调用Editor.md的实例对象，在onload要用this调用方法。

**Comment by tylerlong** [comment]
是否能检测所有模块都加载完？onload事件中的代码，应该能够假设所有的都已经加载完了，否则就太奇怪了。 那不如名字改为 onloading

实际的代码可能会很复杂，比如editor是全局变量，在onload中调用了其它的全局函数， 这个全局函数中又调用了editor的某些方法。 这时候应该没办法用this。

**Comment by pandao** [comment]
异步加载依赖模块，又想同步调用， 目前可以说“无解”，在些应用条件又不能用ES6。

**Comment by pandao** [comment]
搞清楚了，发现你提的问题的原因了，原来`settings.onload`在`CodeMirror.on("change")`之前触发了，change事件还没注册就触发了onload回调。

**Comment by pandao** [comment]
@v1.1.7 fixed.
