### ISSUE TITLE
只展示HTML时 无法改变主题，，

### ISSUE THREAD

**Issue by sqchenxiyuan** [pandao/editor.md#251]
我想改成dark主题，但就是不行
在初始创建时不能，，
然后我用了setPreviewTheme('dark');还是不能，，求助，，

**Comment by pandao** [comment]
@sqchenxiyuan setPreviewTheme 方法是编辑模式时用的

**Comment by sqchenxiyuan** [comment]
@pandao 那么在展示模式的时候怎么是设置样式啊、或者如何自定义样式，，官网给的只有编辑模式的案例

**Comment by pengxianggui** [comment]
同问哦。

**Comment by cfk1996** [comment]
同问+1，谢谢~~~

**Comment by cfk1996** [comment]
@pandao 在非编辑模式下怎么改变theme?谢谢！

**Comment by zZ-GitHub** [comment]
可以自己改css @cfk1996

**Comment by pandao** [comment]
@sqchenxiyuan @cfk1996 非编辑模式下，需要你们自己（参考 `editormd.preview.css`）去自定义，也只有你们知道自己想什么样的。
