### ISSUE TITLE
可添加一个导出文本的按钮

### ISSUE THREAD

**Issue by GitVendor** [pandao/editor.md#260]
在线编辑的一个主要的用途是摆脱本地编辑器，是否可以添加一个保存到本地的选项，生成**.md文件。

**Comment by TechQuery** [comment]
这个应该只有支持 HTML 5 `<a download="file.ext" />` 的浏览器才能支持吧？

**Comment by pandao** [comment]
@GitVendor 按钮可以自己添加，下载文件需要服务端支持，Editor.md 定位为一个前端 Markdown 编辑器组件，所以不做这些工作。

**Comment by pandao** [comment]
自定义工具栏按钮的示例：http://editor.md.ipandao.com/examples/custom-toolbar.html
