### ISSUE TITLE
只想把markdown代码 转换为 html代码，怎么做？

### ISSUE THREAD

**Issue by zhaoguoquan** [pandao/editor.md#263]
目标：把给定的markdown代码 转换为 html代码，怎么做？

有没有一个函数可以做这事？ 必须要使用编辑器的整个组件吗？ 看了项目的各种示例，没发现怎么做。求教？

**Comment by pandao** [comment]
@zhaoguoquan 示例：[http://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](http://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html)

**Comment by TechQuery** [comment]
@zhaoguoquan https://github.com/chjj/marked
Editor.md 也是基于它来解析 MarkDown 的~

**Comment by noxue** [comment]
在编辑的时候，在客户端转换成html之后提交即可，同时提交两份，一个转之前的，用于编辑，一个转之后的，用于显示。
估计楼主主要考虑到seo问题
