### ISSUE TITLE
有计划支持待办事项吗

### ISSUE THREAD

**Issue by zhaopengme** [pandao/editor.md#266]
github有支持待办事项

语法如下.咱们有计划支持吗?

```
- [ ]
- [x]
```

**Comment by pandao** [comment]
@zhaopengme 这个支持很早就有了，示例：[http://pandao.github.io/editor.md/examples/task-lists.html](http://pandao.github.io/editor.md/examples/task-lists.html)

**Comment by zhaopengme** [comment]
刚刚看到 closed 了,好久没有看到有更新了
