### ISSUE TITLE
能否把依赖的第三方组件独立出来？

### ISSUE THREAD

**Issue by snowpine** [pandao/editor.md#28]
Editor.md编辑器依赖的第三方组件，直接在lib文件夹了，但系统已经在其它地方加载了某些第三方组件，比如codemirror。导致系统中的组件重复了。

**Comment by pandao** [comment]
可以通过配置项`path`来指定依赖的第三方组件`lib`的位置，不过依赖的CodeMirror模块我已经合并了。既然用了Editor.md，一般情况下，大多是不会再用到CodeMirror的，可以直接用Editor.md加载的CodeMirror。

**Comment by snowpine** [comment]
恩，你的意思我理解！我也能安装起来。谢谢！
我是用的Yii2，用composer安装了Editor.md，安装在vendor/bower目录下，但因为vendor不在web可访问目录下，所以我必须用Yii2的AssetBundle把Editor.md发布出去，发布好的文件在一个随机目录下。
我必须发布Editor.md的整个目录，不能只发布js和css，否则依赖包对应不起来，这时候美中不足的是很多不需要的文件也发布出来了，比如jquery.min.js。

**Comment by pandao** [comment]
@snowpine  `jquery.min.js`不是动态加载的，所以不用发布；

我考虑要不要把`jquery.min.js`移出`lib`，算是我这边没注意。

**Comment by pandao** [comment]
@v1.1.8 fixed.
