### ISSUE TITLE
markdownToHTML时报错

### ISSUE THREAD

**Issue by ydiego** [pandao/editor.md#284]
`console.log(editormd.markdownToHTML("test-editormd"));`
`marked is not defined`
3919行的  `editormd.$marked = marked;`

**Comment by toxicyu** [comment]
em..把marked.min.js引用解决  不过又报codemirror错误了
`Cannot read property 'insertBefore' of null`

**Comment by ycrao** [comment]
貌似你自己的问题吧，请先找准对应id是否正确

**Comment by callmeyan** [comment]
好像不能使用marked.min.js

**Comment by TechQuery** [comment]
@toxicyu @callmeyan 

**Editer.md** 会自动加载 **同级 `lib` 目录**下的 `marked.min.js` 的~

**Comment by toxicyu** [comment]
@ycrao @TechQuery   感谢你们的回答 正常使用是没问题的，我是看到这个方法的时候以为可以通过调用这个方法去转化一段markdown语法  是我没表达清楚 抱歉

**Comment by TechQuery** [comment]
@toxicyu 为何不直接用已经被引入的 `window.marked()`？

**Comment by z-young7** [comment]
@ydiego 请问阁下最后是如何解决的呢，同样困惑中，为了实现markdown源码在另一页面以html的形式展示出来，多谢！

**Comment by z-young7** [comment]
![image](https://user-images.githubusercontent.com/23393828/52933498-874f3b00-338e-11e9-86e3-966733bbe967.png)
已解决，主要是需要引入相应如上所示的js文件。
