### ISSUE TITLE
markdown html预览问题（非编辑状态）

### ISSUE THREAD

**Issue by headwindfly** [pandao/editor.md#289]
我的内容存的是markdown

为了seo，想先将markdown内容输出，等editor.md将markdown转成html的时候，将原本的markdown隐藏。

问题：editor.md将markdown转成html的事件有吗？或者有没有其他方法？

**Comment by pandao** [comment]
@headwindfly 

参考示例：[https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html)，使用 `editormd.markdownToHTML()` 方法，这个方法是同步的会返回一个容器层 jQuery 对象，之后就可以隐藏 Markdown 了：

```javascript
var $container = editormd.markdownToHTML('id', {
     //...
});

$container.find("textarea").remove();
```

**Comment by headwindfly** [comment]
好的 感谢
