### ISSUE TITLE
Link 和 Heading 不兼容

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#29]
如下代码：

`## [Markdown Basics](http://daringfireball.net/projects/markdown/basics)`

表示既是link，也是heading 2.

Github可以完美显示：

## [Markdown Basics](http://daringfireball.net/projects/markdown/basics)

editor.md 不支持。 这应该算是一个比较严重的影响使用的bug。

**Comment by pandao** [comment]
我看看是不是因为marked不支持。

**Comment by pandao** [comment]
marked本身是支持的，是我的问题，因为Editor.md会给每个heading生成一个锚点链接，所以才导致这个问题的。

**Comment by pandao** [comment]
@v1.1.9 fixed.
