### ISSUE TITLE
使用起来感觉比较卡

### ISSUE THREAD

**Issue by zhmm** [pandao/editor.md#30]
中文输入或者英文输入时候，cpu明显比较高。
全部默认页面，不知道是不是自己没设置对？
关掉实时预览功能也有点卡
谢谢

**Comment by pandao** [comment]
最好是能提供具体的环境（例如系统，浏览器，硬件等等信息），还有具体的markdown内容。

目前的性能情况是，在实时预览时，如果全开启ToC、流程图、科学公式和时序图这些Markdown扩展支持，并且在Markdown文档内容很多的情况下，性能会有所下降，低配置的机子会感觉比较卡。

我这边测试的结果是，如果全是“标准”的markdown内容，性能还是很不错的。

**Comment by tylerlong** [comment]
我感觉不到卡。 我的电脑是2012款的Mac mini，配置比较一般。

我下载了著名的Mou编辑器，那才叫卡。相比之下editor.md 比它快多了。

CPU 占用稍微有点高，在能接受的范围内。我怀疑，如果是5年以上历史的旧电脑，真的可能会卡。

**Comment by zhmm** [comment]
使用的是实例中的完整实例页面
![e2680c6f-c694-41c0-b312-43471afeb62e](https://cloud.githubusercontent.com/assets/3608860/6479603/e94cbdc2-c282-11e4-9cf1-c5338d5ea1a0.png)

**Comment by pandao** [comment]
@zhmm 按理说在Mac os x系统上Editor.md性能应该是最好的。

另外火狐如果装太多扩展，也是会很卡的。

**Comment by zhmm** [comment]
可能是开启太多扩展加机器老原因造成的，使用示例中的“简单示例” 正常。
流程图，时序，公式这些暂时用不到，先关掉了。
非常感谢你们做的这个产品，找这种编辑器找了好久。
谢谢 :)

**Comment by pandao** [comment]
@zhmm ^_^ 也谢谢你的认可，欢迎你继续关注Editor.md和反馈问题。
