### ISSUE TITLE
emoji表情包[github emoji]无法显示

### ISSUE THREAD

**Issue by geasyheart** [pandao/editor.md#300]
希望作者可以修改一下这个问题

**Comment by gzw95322** [comment]
目测是原来的获取图片的url失效了，我把原有的链接换成http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/，就可以了

**Comment by geasyheart** [comment]
嗯，非常感谢！

**Comment by Naiba01** [comment]
请问在哪个源文件修改链接？

**Comment by geasyheart** [comment]
直接在引用emoji表情那换成新地址就行


来自 魅族 MX4

-------- 原始邮件 --------
发件人：Javen Leung <notifications@github.com>
时间：周日 12月18日 11:40
收件人："pandao/editor.md" <editor.md@noreply.github.com>
抄送：X180 <geasyheart@163.com>,Author <author@noreply.github.com>
主题：Re: [pandao/editor.md] emoji表情包[github emoji]无法显示 (#300)

**Comment by gzw95322** [comment]
源文件里面搜emoji-cheat-shell就找到了

**Comment by Naiba01** [comment]
找到了谢谢

**Comment by pandao** [comment]
统一回复：原来的 Emoji 图片域名路径变了，新版本会改正，临时解决方案：

```javascript
editormd.emoji = {
     path  : "https://www.webfx.com/tools/emoji-cheat-sheet/graphics/emojis/",
     ext   : ".png"
};
```
