### ISSUE TITLE
Emoji Path Bug

### ISSUE THREAD

**Issue by Prof-GenShi** [pandao/editor.md#308]
Emoji link changed.

old: http://www.emoji-cheat-sheet.com/graphics/emojis/
new: http://www.webpagefx.com/tools/emoji-cheat-sheet/

2016.11.06

**Comment by Prof-GenShi** [comment]
感谢来信，是url路径变了，我已经改好


在2017年01月06日 12:11，飞扬 写道:

@Prof-GenShi 重载配置，访问不到，是因为墙的问题，不代表该网站不存在

#311

**Comment by pandao** [comment]
Duplicate of #300
