### ISSUE TITLE
项目地址的http访问无效

### ISSUE THREAD

**Issue by leux0** [pandao/editor.md#309]
# 项目地址的http访问失效，只支持https访问
## http无法访问，例：
http://pandao.github.io
http://pandao.github.io/editor.md/
http://pandao.github.io/editor.md/examples/index.html

## https访问正常：
https://pandao.github.io
https://pandao.github.io/editor.md/
https://pandao.github.io/editor.md/examples/index.html

**Comment by pandao** [comment]
@leux0 好像是 Github 本身强制使用 HTTPS。
