### ISSUE TITLE
KaTex 不要再用cdn的版本了

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#31]
所有的第三方软件包都用的本地的拷贝，只有KaTex用的是CDN的版本：

```javascript
// 使用国外的CDN，加载速度有时会很慢，或者自定义URL
editormd.katexURL  = {
    css : "//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.1.1/katex.min",
    js  : "//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.1.1/katex.min"
};
```

这很另类，也带来了问题。 比如用户没有联网的情况下不能用。还有用户通过文件系统直接打开的时候也不能用 (`file://`开头的URL)

建议采用包管理器来使用KaTex。比如用bower的话就是 `bower install katex-build`。

参考： https://github.com/Khan/KaTeX/issues/114

**Comment by pandao** [comment]
起先考虑使用CDN是不想整个项目文件包太大，所以直接使用了CDN，并且设置了可以自定义KaTeX加载URL。

**Comment by tylerlong** [comment]
没必要把整个软件包都包含到editor.md中，只要在bower.json中设置为依赖项就可以了。

```javascript
"dependencies": {
    "underscore": null,
    "jquery": null,
    "katex-build": null
}
```
`bower install` 一条命令就全装好了。
包管理器就是这样用的。你把第三方的库都直接包含进来，体积肯定大。

之前也有人反映了类似的问题： https://github.com/pandao/editor.md/issues/28

**Comment by pandao** [comment]
倒是可以这样，但是不一定都在用`bower`，要这样做也只能作为多种安装方式之一，估计整体结构会变动太大，再考虑考虑。

**Comment by pandao** [comment]
可以通过`editormd.katexURL`来自定义KaTeX地址，关于是否使用CDN或者Bower安装到本地的决定权还是交给使用者。
