### ISSUE TITLE
在laravel后台想引进这个编辑器，但是不可以，样式显示不出来，代码如下

### ISSUE THREAD

**Issue by hyrbridword** [pandao/editor.md#313]
![image](https://cloud.githubusercontent.com/assets/19897885/20202404/e5bb7f28-a7f9-11e6-9517-095abb028c8a.png)

**Comment by ycrao** [comment]
@ChenPHPER 可以试试本人的扩展包 https://github.com/douyasi/laravel-editor-md

**Comment by jackslowfuck** [comment]
审查下元素 看看js或者css
