### ISSUE TITLE
启用 CodeMirror Search/Replace 功能

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#32]
例子： http://codemirror.net/demo/search.html

Search功能倒是可以用浏览器内置的。 Replace功能就没办法了。

**Comment by pandao** [comment]
CodeMirror的替换功能replace是按Ctrl+shift+F，先Search，然后Enter，显示With对话框填写要替换的，再回车，这时会提示YES or NO

**Comment by pandao** [comment]
@tylerlong 接受你的提议，打算列入下个大版本v1.2，作为新增的功能。不过要等段时间，先让v1.x能有尽可能的测试和修复Bug。

**Comment by pandao** [comment]
v1.x系列版本启用搜索和替换功能的方法：

```javascript
var testEditor = editormd("test-editormd", {
	width: "90%",
	height: 540,
	path : '../lib/',
	onload : function(){
		editormd.loadCSS("../lib/codemirror/addon/dialog/dialog");
		editormd.loadCSS("../lib/codemirror/addon/search/matchesonscrollbar");
		editormd.loadScript("../lib/codemirror/addon/dialog/dialog");
		editormd.loadScript("../lib/codemirror/addon/search/searchcursor");
		editormd.loadScript("../lib/codemirror/addon/search/search");
		editormd.loadScript("../lib/codemirror/addon/scroll/annotatescrollbar");
		editormd.loadScript("../lib/codemirror/addon/search/matchesonscrollbar");
	}
});
```

**Comment by tylerlong** [comment]
我试了下，上面的方案可行。

有一些小问题（CodeMirror的问题，不过既然用了CodeMirror，也就继承了这些问题。）

- 搜索功能只能全部高亮，不能交互式挨个高亮
- 高亮后想取消高亮，只能再次打开搜索框
- 替换和全部替换，其实应该做成button，而不是靠快捷键来区分
- 默认不区分大小写，除非你写正则。 但是最终用户有多少是懂正则的？

整体感觉非常粗糙。仅仅是能用而已。当然这是CodeMirror addon的问题。需要调查下是否有更好用的addon，或者自己写一个难度有多大？

相比之下，ACE的搜索替换功能就相当赞： http://ace.c9.io/build/kitchen-sink.html

**Comment by pandao** [comment]
暂时先用CodeMirror默认的解决方案，更好的解决方案再慢慢改进。
不过，这里找到了一个，ACE应该也是用这个插件，[https://github.com/coderaiser/cm-searchbox](https://github.com/coderaiser/cm-searchbox)

**Comment by pandao** [comment]
v1.2 计划采用 [cm-searchbox](https://github.com/coderaiser/cm-searchbox) 这个插件来实现。

**Comment by pandao** [comment]
整合 [cm-searchbox](https://github.com/coderaiser/cm-searchbox) 出了问题，看来得自己写一个了。

**Comment by tylerlong** [comment]
cm-search 太新了，有问题很正常。

具体什么问题？

**Comment by pandao** [comment]
@tylerlong  嗯，v1.2 暂时还是采用CodeMirror默认的搜索Addon。

**Comment by pandao** [comment]
@v1.2.0 support search / replace.

**Comment by aliqiang** [comment]
https://github.com/coderaiser/cm-searchbox
已经使用了searchbox.js
直接输入alt+cmd+f，不能打开替换对话框。必须先用cmd+f打开搜索框，然后输入alt+cmd+f，才会切换到替换对话框。
那么为了能够直接打开替换对话框，做了如下修改
在searchbox.js中找到如下代码
CodeMirror.defineOption('searchbox', false, function(cm) {
}
然后增加cmd-alf-f的快捷键绑定
'Cmd-Alt-F': function() {
                if (!Search){
                	Search  = new SearchBox(cm);
                }
                Search.show(null,true);
            }

那么现在你输入cmd-alt-f就可以直接打开对话框了
