### ISSUE TITLE
支持 Task Lists

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#33]
GitHub 支持下面的语法

```markdown
- [ ] This is a complete item
- [x] This is an incomplete item
```

效果是这样的：

- [x] This is a complete item
- [ ] This is an incomplete item

根据这个文档： https://guides.github.com/features/mastering-markdown/

Task Lists属于是Github Flavored Markdown的内容。

既然editor.md支持GFM，那么就应该支持这个特性。

我个人感觉这个特性跟Github并没很直接的关系，算是一个比较通用的东西。

关键看marked能不能支持。

**Comment by pandao** [comment]
marked估计不支持，可能要自己写解析规则。

**Comment by pandao** [comment]
test demo finish

**Comment by pandao** [comment]
@v1.2.0 support GFM task lists. [https://pandao.github.io/editor.md/examples/task-lists.html](https://pandao.github.io/editor.md/examples/task-lists.html)
