### ISSUE TITLE
随便写个文字怎么就被当做代码块了？

### ISSUE THREAD

**Issue by liycode** [pandao/editor.md#330]
随便写个文字怎么就被当做代码块了？
![20161227200330](https://cloud.githubusercontent.com/assets/12079366/21499307/a49dc3f8-cc6f-11e6-8366-ecf79276fc75.png)

**Comment by liycode** [comment]
使用的是Markdown转HTML的显示处理这个功能，请教啊

**Comment by Codle** [comment]
楼主解决了吗 我现在文章第一排就是这样

**Comment by liycode** [comment]
@Codle   我好了。

```
<div id="editormd-view">
    <textarea id="append-test" style="display:none;">$article</textarea>
</div>
```

```
editormd.markdownToHTML("editormd-view", {
	markdown : $("#append-test").text(),
	htmlDecode : "style,script,iframe",  // you can filter tags decode
	emoji : true,
	atLink : false
});
```

**Comment by ANYMS-A** [comment]
@liycode 您好我遇到了同样的问题 就是第一行markdown会被渲染成代码块，按照你的方式并没有解决此问题？
请问具体造成这个问题的原因是什么呢？

**Comment by ANYMS-A** [comment]
> 楼主解决了吗 我现在文章第一排就是这样

请问您这个问题有解决吗？求教！

**Comment by ANYMS-A** [comment]
> 随便写个文字怎么就被当做代码块了？
> ![20161227200330](https://cloud.githubusercontent.com/assets/12079366/21499307/a49dc3f8-cc6f-11e6-8366-ecf79276fc75.png)

此问题是由于<textarea></textarea>的语法问题造成的

应该假设{{ post.body }}是从database中取出的markdown文本那么textarea部分应该像下面这样写：
```
<textarea id="append-test" style="display:none;">{{ post.body }}</textarea>
```
而不是
```
<textarea id="append-test" style="display:none;">
    {{ post.body }}
</textarea>
```
像下面这样写，markdownToHtml就会把文本的第一行转化为代码块
