### ISSUE TITLE
最近在fis3、VUE项目里尝试这个的时候总是不能整合不知道能不能添加一个example

### ISSUE THREAD

**Issue by lenxeon** [pandao/editor.md#332]
最近在fis3项目里尝试这个的时候总是不能整合不知道能不能添加一个example

**Comment by lenxeon** [comment]
感觉应该是amd的问题

**Comment by cheneyliu** [comment]
为啥还用 amd ， cmd 不是很好吗

**Comment by TechQuery** [comment]
@lenxeon @cheneyliu 为啥还用 CMD？AMD 不是很好吗？

**Comment by lenxeon** [comment]
@cheneyliu @TechQuery  你们两有在vue、fis3中使用过这个。我没有集成成功。

**Comment by cheneyliu** [comment]
....fis3 做多页打包, 如pc端网页处理, 手机端的我基本用webpack, 现在手机项目都是vue的

**Comment by lenxeon** [comment]
@cheneyliu 你有空的时候麻烦试一下这个吧。要是可行的话请贴一下关键部分的代码，谢谢。我尝试的时候没有报错，但编辑器也不出来。
