### ISSUE TITLE
图片上传的优化建议

### ISSUE THREAD

**Issue by supersdar** [pandao/editor.md#334]
https://github.com/etoah/LucienMdEditor
能不能把这个项目的功能整合到editor.md?

**Comment by wxd237** [comment]
我也想要这个功能啊，找了好久，但这个好像要后端配合

**Comment by ycrao** [comment]
wang-editor 已经实现了，可以参考看看 https://github.com/douyasi/laravel-wang-editor

**Comment by supersdar** [comment]
wang-editor 不支持markdown

**Comment by ycrao** [comment]
@supersdar 你可以参考它实现方式，如果可以，提交自己的pull request

**Comment by wxd237** [comment]
试了下[paste.js](https://github.com/layerssss/paste.js) 发现跑不起来。有谁能研究下。

**Comment by pandao** [comment]
Duplicate of #219
