### ISSUE TITLE
能否支持GFM emoji

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#34]
http://www.emoji-cheat-sheet.com/

:panda_face:

:angel:

:cherries:

这个其实也算是 GFM 的标准之一。能支持最好。

我个人觉得能支持一些流行的字体图标更好，比如font-awesome.

`:fa-truck:` 就显示这里卡车的图标： http://fortawesome.github.io/Font-Awesome/icon/truck/

支持字体图标这个属于额外的功能了，我想至少应该能够支持标准的GFM emoji

**Comment by pandao** [comment]
原本有设想过，不过当时没有考虑优先实现，我看看能不能列入v1.2新增功能。

**Comment by pandao** [comment]
test demo finish.

**Comment by pandao** [comment]
@v1.2.0 support gfm emoji.
