### ISSUE TITLE
不支持HTML和Markdown混搭

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#35]
```
<div style="color:red;">

## heading 1

</div>
```

启用html标签识别之后也不支持。

这个是支持的：  https://markdown-it.github.io/

考虑是否支持用户自己更换markdown解析引擎？ 通过配置的方式选择到底是marked还是markdown-it

**Comment by pandao** [comment]
1、html和markdown混搭（相互嵌套），这也太不按套路出牌了吧？markdown编辑器还是以markdown为主。有时会想想太多markdown扩展语法是否正确。

2、没打算支持切换markdown解析引擎，这样会使程序改变很大，增加复杂程序。原本和后续许多解析规则都是基于`markded`的。
