### ISSUE TITLE
emoji 表情加载不出来

### ISSUE THREAD

**Issue by jjjjyx** [pandao/editor.md#358]

**Comment by xsq871839012** [comment]
![image](https://cloud.githubusercontent.com/assets/9389419/23290641/4a046b1c-fa8d-11e6-94da-0f443356ba17.png)
检查了一下 发现官方的地址不对我改成了这个

**Comment by SophieYe** [comment]
照你的改了之后仍然不显示啊

**Comment by xsq871839012** [comment]
@SophieYe  http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/
这个网址

**Comment by SophieYe** [comment]
@xsq871839012 啊~~~谢谢，谢谢，终于好了 😆

**Comment by tiancegit** [comment]
嗨,能请问下,这是那个文件下的配置项吗?
大概遇到同样的问题.但是找不到这个配置项!

**Comment by SophieYe** [comment]
![image](https://cloud.githubusercontent.com/assets/5378095/23447849/ad63d4b4-fe88-11e6-8d0d-3493ead791b3.png)
请问这个html标签预览的时候怎么去掉呢

**Comment by xsq871839012** [comment]
@tiancegit  
![image](https://cloud.githubusercontent.com/assets/9389419/23584546/a77d1bf4-019f-11e7-8e83-a03c189fa230.png)

在源码中有这个一段
那我们自己直接修改path值就ok
```
editormd.emoji.path = "http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/";
this.editormd = editormd("post-editormd", {
            path              : '../editormd/lib/',
            emoji             : true,
            imageUpload       : true
            // ...
});
```

**Comment by xsq871839012** [comment]
@SophieYe  这个你看文档就好 大概是开始html解析相关的
[识别和解析HTML标签](https://pandao.github.io/editor.md/examples/html-tags-decode.html)
![image](https://cloud.githubusercontent.com/assets/9389419/23584581/5d9742e8-01a0-11e7-99f1-774b006e158f.png)

**Comment by AdventureBoy** [comment]
修改什么文件？

**Comment by xsq871839012** [comment]
@AdventureBoy  不用修改文件，单纯的想开启emoji 表情功能只要加入如下代码
`editormd.emoji.path = "http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/";`

**Comment by cnjiangjun** [comment]
https://github.com/SemiWarm/SemiWarmAdminPhotos/blob/master/emoji.zip 这里也可以下载

**Comment by chenshun00** [comment]
除了要加上这一行代码之外，`editormd.emoji.path = "http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/";`  ，还要开启 `emoji` 👍   `emoji : true`

**Comment by pandao** [comment]
Duplicate of #300
