### ISSUE TITLE
editor 自动保存

### ISSUE THREAD

**Issue by wangjianan1103** [pandao/editor.md#360]
您好，我十分喜欢这个编辑器，我想请教一下，自动保存具体应该怎么实现，每次保存都要请求一次后端么？

**Comment by Ryongyon** [comment]
是个人使用的场景吗？大致的思路就是:
启动——检测目录是否存在xxxxx.md——(存在:创建editor.md，载入xxxxx.md)(不存在:创建editor.md)——定时任务——每30秒执行一次——保存内容到xxxxx.md——发表/保存内容——删除xxxxx.md
