### ISSUE TITLE
Download as HTML/PDF

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#37]
能否提供 Download as HTML/PDF 功能？就是用户编辑好一个markdown文件，可通过快捷按钮，下载为HTML或者PDF。

下载为HTML的时候，下载的东西是一个zip包，里面包含了必须的所有的HTML/JS/CSS, 解压缩后直接就可以通过浏览器打开阅读。

下载为PDF就不多解释了，PDF格式跨平台性比较好，大部分人的电脑都能直接打开看，是比较适合分发的格式。

仅仅是一个提议， 不知道这个是否可以放倒editor.md中去实现。

也许放倒网站服务器端去实现比较好，js实现有点费劲。

**Comment by pandao** [comment]
这个就不属于Editor.md应该做的事了，有相应的NPM包或者用后台语言实现。
