### ISSUE TITLE
安装起来太麻烦，差评

### ISSUE THREAD

**Issue by macnie** [pandao/editor.md#373]
教程写的是什么啊。安装起来太麻烦，引用什么的也不说清楚。

**Comment by lifei6671** [comment]
很简单啊。是你自己不会吧。

**Comment by SherHoooo** [comment]
要是能支持npm 安装就好了

**Comment by Ryongyon** [comment]
@lifei6671 并不赞同你的话，你刚学前端的时候如果去网上搜索某资源的时候，如果就作者就丢出来个压缩包，文档也写不清楚，你又看不懂源码、结构，你怎么办？这里是讨论 问答区，既然有人提问了，就应该给予友好的回答，而不是丢一句：“很简单啊，是你自己不会吧”，如果人人都这种心态，那岂不是一件很可怕的事情？既然你不想耐心的指导，回答，那就关掉网页呗，何必泼人冷水？说一些不痛不痒的话。
===================================================
@macnie 
完整示例：https://pandao.github.io/editor.md/examples/full.html
简单示例：https://pandao.github.io/editor.md/examples/simple.html

右键——查看源码，看看示例中分别引入了什么文件，也可以把源码直接copy到本地，放到根目录运行就大概知道了。具体每个目录是做什么的，你可以上网自行了解一下，或是问问别人。不会我们就问，而不是直接上来就说给差评，那你跟某宝的“职业差评师”有什么区别？一码归一码事

**Comment by lifei6671** [comment]
@Ryongyon **该项目是开源项目，作者虽然有义务维护项目，但是没义务教会虽有人。自己不会可以虚心请教，一点虚心都没有直接说差评，如果你是项目维护者，你什么心情？
最讨厌的就是那种免费用别人的还给差评的人。**

**Comment by x373241884y** [comment]
是啊，最烦这种不思考直接下结论的了，主分支里面有例子源码，有测试例子，有在线例子，它看见你，你却无视它，是谁的错？

**Comment by lxepoo** [comment]
给个满汉全席还不够，还指望一勺一勺喂你吃吗。

**Comment by SherHoooo** [comment]
唔，通过读example里面的代码基本上都能把功能点搞清楚。

**Comment by yycyycyy** [comment]
非前端握爪，原以为是个IDE，其实是个依赖包。

**Comment by TechQuery** [comment]
@yycyycyy 你从中文 ReadMe 的哪句话看出这是个 IDE 的？
