### ISSUE TITLE
为何v1.2版本dist目录不见了？

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#38]
之前的版本有dist目录，里面放置的是压缩过的可以用作生产环境的js和css文件。

**Comment by tylerlong** [comment]
相关的压缩文件，在其它目录还是可以找到的。

**Comment by pandao** [comment]
v1.2.0 为了实现插件机制及其module化加载，把editormd.js移到根目录下了，所以移除dist目录。
