### ISSUE TITLE
为什么上传的图片没有名称

### ISSUE THREAD

**Issue by Ryongyon** [pandao/editor.md#386]
能够正常上传图片，但是图片是没名称的：".jpg"，只有扩展名，请问是什么原因？

**Comment by Ryongyon** [comment]
噢，忘记说了，用的是开发版才出的问题
1.5版本正常

**Comment by AbdullahKhdir** [comment]
Hello there,

I'm having the same issue everytime when i upload an image the following is always returned 

did you solve this issue yet, or even recognised what exactly the issue ?

```TEXT
Uncaught SyntaxError: Unexpected token { in JSON at position 104
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)
```
