### ISSUE TITLE
保存的时候在数据库里面的是markdown标识  怎么转化为html标签

### ISSUE THREAD

**Issue by lishoubiaobb** [pandao/editor.md#389]
例如 现在我的编辑器里面的是  *你好*  两个*符号表示是斜体   可在前台显示的时候不是斜体的你好两个字  而是原原本本的  *你好*  markdown标识

**Comment by Mr-Pro** [comment]
去官网了解一下markdowntoHTML吧

**Comment by zhenqicai** [comment]
@Mr-Pro 你好 editormd集成到java web项目中，点击上传图片的图标，却提示：Error: imageDialog plugin is not found, you are not load this plugin. 加载 插件失败！ plugins文件夹也添加到项目里了！

**Comment by zZ-GitHub** [comment]
@zhenqicai 别这样问啊

**Comment by zZ-GitHub** [comment]
@zhenqicai 关注的人 会关注的 你复制粘贴我这就是 一份邮件

**Comment by Mr-Pro** [comment]
@zhenqicai 这里的话需要你自己写一个用于上传图片的链接，然后在md初始化的时候提供一个url给它，当图片上传到服务器后你处理成功需要做出反馈（JSON反馈信息）

**Comment by Mr-Pro** [comment]
@zhenqicai 具体的你可能需要去官网看下，还有就是善用浏览器的开发工具

**Comment by pandao** [comment]
@lishoubiaobb Markdown 源码显示为 HTML 示例：http://editor.md.ipandao.com/examples/html-preview-markdown-to-html.html
