### ISSUE TITLE
请问这软件是不是侵权了. 

### ISSUE THREAD

**Issue by ilessy** [pandao/editor.md#390]
https://www.romanysoft.net/markdownd/ 
就是作者的软件包了个壳子也没见哪里声明作者的MIT协议了. 就直接拿来卖, 不厚道啊.

**Comment by stephencode** [comment]
现在 **markdown** 在线版、客户端版优秀的很多，而且都是免费的。。拿来卖我真想不通谁会买= =

**Comment by Holly199** [comment]
同感~~~
