### ISSUE TITLE
mailto: 链接有问题

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#40]
`[email me](mailto:test@test.com)`

GitHub 正常：
[email me](mailto:test@test.com)

**Comment by tylerlong** [comment]
一个临时的解决方案：

```javascript
editormd.regex.atLink = /(?:^|\W)@(\w+)/g;
```

**Comment by pandao** [comment]
这个正则不行，我这边加了一个是否为邮箱地址的判断。

**Comment by tylerlong** [comment]
正则是没办法精确判断邮箱的。 

比如：`a@b`  也可以是合法的邮箱 `b` 是本地的server host name

**Comment by pandao** [comment]
test@locahost 之类的就不自动转成链接了。

**Comment by pandao** [comment]
@v1.3.0 fixed.
