### ISSUE TITLE
请问可以外部导入markdown么

### ISSUE THREAD

**Issue by lineng1993** [pandao/editor.md#406]
博客中用了editor.md编辑器，在写文章的时候确实很好用，编辑的时候呢，有方法或者设置导入我的markdown？？

**Comment by pandao** [comment]
@lineng1993 可以在工具栏上自定义一个按钮，然后使用 FileReader API 读取文件内容，设置到编辑器。

http://editor.md.ipandao.com/examples/custom-toolbar.html
