### ISSUE TITLE
自动把邮件地址变成链接有问题

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#41]
`test@test.com`

GitHub正常

test@test.com

**Comment by tylerlong** [comment]
应该是新增的这个特性导致的：

https://pandao.github.io/editor.md/examples/@links.html

**Comment by tylerlong** [comment]
同时 mailto: 的冒号跟 emoji 的冒号也有冲突

email 地址真的是没法好好显示了。

**Comment by tylerlong** [comment]
一个临时的解决方案：

```
atLink: /(?:^|\W)@(\w+)/g,
```

`@`前面不能是其它的字母数字等等，否则就认为是邮件地址。

**Comment by pandao** [comment]
切实是没考虑到邮件地址也有个@，一个疏忽。

**Comment by pandao** [comment]
@v1.3.0 fixed.
