### ISSUE TITLE
输入一段代码后，无法保存

### ISSUE THREAD

**Issue by CacheTechLtd** [pandao/editor.md#412]
`public function count_search($conditions) {
		return DB::result_first('SELECT COUNT(*) FROM %t %i %i', array(
			$this->_table,
			$this->_alias,
			$this->search_condition($conditions)
		));
	}`

即时我删除后，也无法保存了，不知道为什么。

**Comment by CacheTechLtd** [comment]
测试了一下，把SELECT删除了，就没有问题

**Comment by pandao** [comment]
@CacheTechLtd 请检查你所说的“保存”。
