### ISSUE TITLE
开启 htmlDecode 后，标题里不能嵌套其他格式

### ISSUE THREAD

**Issue by Liiijabn** [pandao/editor.md#413]
开启 htmlDecode 后，如果在标题里加粗（有些人确实会这么写(⊙﹏⊙)b），或者斜体，比如 `## 标题 * 斜体*`， `## 标题 **加粗**`

这个时候解析会出错。我看了一下，原因应该是：解析标题时，会自动添加 `<a>` 标签，并且带 name 属性，name 的值为标题内容，如果标题带格式，那在name的值里面，会带`<>`等内容，这个时候 `filterHTMLTags`方法传进来的 `html`  @参数，标记不完整，会报错 `Cannot read property 'attributes' of undefined` 

这应该算是个 bug 吧，希望可以处理一下，谢谢！ 

#337 #261

**Comment by pandao** [comment]
@Liiijabn 开启 htmlDecode 后，`## 标题 **加粗**` 可以正常解析呀。

**Comment by Liiijabn** [comment]
好久远了😂你是准备继续维护了么？

**Comment by pandao** [comment]
@Liiijabn 有空就会维护。

**Comment by Liiijabn** [comment]
我们之前用了你这个编辑器，有发现一些问题，比如我现在能想起来的一个问题是，文档标题生成的 id，如果标题名称一样，就会重复。但是发现你基本没怎么维护，所以就自己解决了。
