### ISSUE TITLE
发个牢骚，你们包与包之间的管理真的让人心醉

### ISSUE THREAD

**Issue by Ryuurock** [pandao/editor.md#423]
自己试试在webpack下 什么情况，惨不忍睹，各种依赖找不到
害得我手动去单独引用CodeMirror 手动挂到window，你们这个是个模块诶 难道我不是引用一个js就够了？

上传到npm的css 3084行 `.../`什么鬼？

**Comment by choui** [comment]
同问 webpack打包各种报错
