### ISSUE TITLE
支持复选框

### ISSUE THREAD

**Issue by code-artisan** [pandao/editor.md#439]
请问作者有打算支持复选框语法的计划吗？

效果如下所示：
- [x] 复选框（选中）
- [ ] 复选框（未选中）

**Comment by pandao** [comment]
@code-artisan 有支持 GFM Task List，详见示例 [https://pandao.github.io/editor.md/examples/task-lists.html](https://pandao.github.io/editor.md/examples/task-lists.html)

**Comment by code-artisan** [comment]
嗯，看到了，谢谢！
