### ISSUE TITLE
editormd.logo.scss文件中 @font-face有错误

### ISSUE THREAD

**Issue by haoHu** [pandao/editor.md#441]
在editormd.logo.scss文件中， @font-face声明的eot文件的引用路径写错了

```
@font-face {
	font-family: 'editormd-logo';
	src:url('../fonts/editormd-logo.eot?-5y8q6h');
	src:url('.../fonts/editormd-logo.eot?#iefix-5y8q6h') format('embedded-opentype'),
		url('../fonts/editormd-logo.woff?-5y8q6h') format('woff'),
		url('../fonts/editormd-logo.ttf?-5y8q6h') format('truetype'),
		url('../fonts/editormd-logo.svg?-5y8q6h#icomoon') format('svg');
	font-weight: normal;
	font-style: normal;
}
```
`.../fonts/editormd-logo.eot`路径错误，导致使用webpack打包时报错

**Comment by pandao** [comment]
@haoHu 已有相关的 Pull 合并了，等新版本。

**Comment by turnglight** [comment]
@font-face {
  font-family: 'editormd-logo';
  src: url("../fonts/editormd-logo.eot?-5y8q6h");
  src: url(".../fonts/editormd-logo.eot?#iefix-5y8q6h") format("embedded-opentype"), url("../fonts/editormd-logo.woff?-5y8q6h") format("woff"), url("../fonts/editormd-logo.ttf?-5y8q6h") format("truetype"), url("../fonts/editormd-logo.svg?-5y8q6h#icomoon") format("svg");
  font-weight: normal;
  font-style: normal;
}
这个bug又出现了
