### ISSUE TITLE
能不能实现script标签的功能呢！

### ISSUE THREAD

**Issue by taoeer** [pandao/editor.md#442]
能不能实现js的交互呢，比如在编辑器里写了个button，并且在随后写了个script标签未button绑定点击事件，然后再预览区域中点击button能执行js代码？

**Comment by pandao** [comment]
@taoeer 可以试试启用 HTML 标签的解析，详见示例 [https://pandao.github.io/editor.md/examples/html-tags-decode.html](https://pandao.github.io/editor.md/examples/html-tags-decode.html)。

**Comment by taoeer** [comment]
谢谢，是我没有仔细看例子
