### ISSUE TITLE
有整合vue的demo吗？

### ISSUE THREAD

**Issue by talliujobs** [pandao/editor.md#447]
打算用vue来整合一下，结果遇到了很多问题，各种缺少文件。
哪位有成功的demo，可以分享下经验吗？

**Comment by LaveyD** [comment]
https://segmentfault.com/q/1010000009687169?_ea=2574256

**Comment by star7th** [comment]
我在我的项目中整合了。你可以参考下我的实现https://github.com/star7th/showdoc
