### ISSUE TITLE
上面的toobar我可以移动其它地方吗

### ISSUE THREAD

**Issue by huaiguoguo** [pandao/editor.md#448]
toolbar我可以自定到的页面的其它地方吗，像gitbook.com的编辑页面  toolbar在顶部，左侧是目录

**Comment by zZ-GitHub** [comment]
#### 这个大概需要 自己魔改了

**Comment by pandao** [comment]
@huaiguoguo 需要你自己自定义一个工具栏，工具栏上的按钮都要对应的接口方法。
