### ISSUE TITLE
keymap快捷键未屏蔽浏览器默认设置，比如Ctrl-S

### ISSUE THREAD

**Issue by byhgj** [pandao/editor.md#46]
click `Ctrl-S`，能alert，但同时浏览器也弹出保存对话框。

**Comment by pandao** [comment]
能说具体是什么样的场景下出现你说的那种情况？KeyMap是在CodeMirror onfocus时才有效。

**Comment by byhgj** [comment]
输入焦点在编辑框时，测试了firefox和IE，都会弹出浏览器默认保存。
用了kodExplorer，里面的编辑框onfocus保存时就不会弹出浏览器默认Ctrl-S。
这是editor.md测试代码：
```
						var keyMap = {
							'Ctrl-S': function(cm){
								alert('ctrl+s');
							}
						};
						testEditor.addKeyMap(keyMap);
```

**Comment by pandao** [comment]
@byhgj 经测试，确实在FF无法阻止默认的保存动作（IE不会），即使加上`return false;`，暂时无解，有待修正。
