### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by frankie-huang** [pandao/editor.md#472]
在“##”之类的同一行使用反引号`或者**等，无法正常显示：
![2017-10-25 13-23-50](https://user-images.githubusercontent.com/19368107/31982729-a9ade7aa-b98c-11e7-9822-6c690d251f56.png)
控制台报错如下：
![2017-10-25 13-21-22](https://user-images.githubusercontent.com/19368107/31981717-9a5657ce-b987-11e7-85c9-bf08ad5fd9e0.png)
看代码发现jQuery合集对象不能使用"[0]"这样去索引，然后个人自行改成".eq(0)"：
![2017-10-25 14-02-35](https://user-images.githubusercontent.com/19368107/31982851-3c3d55a6-b98d-11e7-8cca-85049bdefd9f.png)

然而显示是可以显示了：
![2017-10-25 14-03-39](https://user-images.githubusercontent.com/19368107/31982886-56e3d29a-b98d-11e7-96f8-c83d90672139.png)
“#### `<head>`” 显示成了 “<head>" class="reference-link"><head>”

**Comment by pandao** [comment]
@frankie-huang 试了一下，并没有这样的问题。
