### ISSUE TITLE
在部分浏览器上工具栏图标无效

### ISSUE THREAD

**Issue by mhcyong** [pandao/editor.md#48]
在使用过程中，发现Chorme,搜狗等浏览器在高速模式下，点击工具栏图标无效。  

与此同时，滚动预览也不成功，更换编辑器或者浏览器切换到兼容模式一切正常。

另外，IPad自带的浏览器，上传图片成功，但是图片地址回调没响应。

**Comment by pandao** [comment]
> 在使用过程中，发现Chorme,搜狗等浏览器在高速模式下，点击工具栏图标无效。
> 与此同时，滚动预览也不成功，更换编辑器或者浏览器切换到兼容模式一切正常。

@mhcyong  经测试没有出现你所反馈的问题，能否提供具体的使用环境信息？

另外，关于iPad的问题，经测试是有这样的问题，这边在查找原因。

**Comment by mhcyong** [comment]
@pandao 电脑是Windows 7 系统，浏览器为Chorme,或者搜狗，访问为官方站点，也许是电脑或系统的原因，因为更换电脑发现使用正常。

**Comment by pandao** [comment]
哦，iPad切实有存在那个问题，已经找到原因并修复了，谢谢你的反馈~

**Comment by mhcyong** [comment]
@pandao 速度真快，赞...

**Comment by pandao** [comment]
@v1.4.0 fixed.
