### ISSUE TITLE
LaTeX 格式数学公式不支持

### ISSUE THREAD

**Issue by Triple-Z** [pandao/editor.md#481]
如：
```latex
$$
A =
\begin{bmatrix}
2 & 2 & 6 \\
3 & 5 & 3 \\
5 & 1 & 2 \\
\end{bmatrix}
 ,
B =
\begin{bmatrix}
2 & 3 & 1 \\
3 & 1 & 2 \\
2 & 1 & 2 \\
\end{bmatrix}
$$
```

无法正常显示

**Comment by wikenator** [comment]
When trying this myself, I see in the web console debug window:

`Error: KaTeX parse error: Expected & or \\ or \end at position 108: … 1 \\3 & 1 & 2 \̲2̲ & 1 & 2 \end{b… 2 `

I was able to render your expression by adding one or two extra slashes to each group of \\:

> $$
> A =
> \begin{bmatrix}
> 2 & 2 & 6 \\\\\\\\
> 3 & 5 & 3 \\\\\\\\
> 5 & 1 & 2 \\\\\\\\
> \end{bmatrix}
>  ,
> B =
> \begin{bmatrix}
> 2 & 3 & 1 \\\\\\\\
> 3 & 1 & 2 \\\\\\\\
> 2 & 1 & 2 \\\\\\\\
> \end{bmatrix}
> $$
>

**Comment by Triple-Z** [comment]
@wikenator Thx, it solved my problem!
