### ISSUE TITLE
为editor.md的图片上传提供简单的java版实现demo

### ISSUE THREAD

**Issue by Tiakon** [pandao/editor.md#485]
你好，我写了一个程序能够解析editor.md图片上传时提交的报文并在服务器端生成图片，希望能够添加到editor.md的图片上传的案例中。

**Comment by Tiakon** [comment]
为editor.md的图片上传提供java版实现案例

**Comment by zZ-GitHub** [comment]
能跨域么

**Comment by Tiakon** [comment]
还没测，应该没问题。记得之前公司就是这么干的。

**Comment by zZ-GitHub** [comment]
厉害了

**Comment by zhenqicai** [comment]
@Tiakon  你好  我也弄了个java 上传图片   图片却上传到服务器上了   但没有返回 图片地址给editor.md界面？    图片上传成功需要返回 json数据给editor.md界面   {"success":1, "message":"上传成功","url":"http://localhost:8080/ssm/upload/155014.png"}

**Comment by Tiakon** [comment]
@zhenqicai 对的

**Comment by zhenqicai** [comment]
@Tiakon  你好   现在我将editormd集成到java  web项目中，然后点击  那个 图片 的图标，却提示：Error: imageDialog plugin is not found, you are not load this plugin.

**Comment by Tiakon** [comment]
@zhenqicai 你去找这个文件plugins->image-dialog，把它添加到你的项目中，不就行了

**Comment by zhenqicai** [comment]
@Tiakon   路径是这样的！
  webapp
        |__assets
                |__vendors
                        |__editormd
                                |__css
                                |__fonts
                                |__images
                                |__lib
                                |__plugins
                                |__editormd.js

**Comment by zhenqicai** [comment]
@Tiakon   添加进去了

**Comment by Tiakon** [comment]
@zhenqicai 还报错吗？

**Comment by zhenqicai** [comment]
@Tiakon  是路径问题还是？默认就是plugins的

**Comment by zhenqicai** [comment]
![](file:///C:/User/wuming/Desktop/a/5341.png)

**Comment by Tiakon** [comment]
@zhenqicai 可以自己定义插件的路径啊

**Comment by zhenqicai** [comment]
@Tiakon   我将editormd单独拿出来，点击图片上传，却弹出图片上传的对话框。

**Comment by zhenqicai** [comment]
@Tiakon 自定义插件路径也弄了，还是一样的！
<script type="text/javascript">
    $(function() {
        var editor = editormd("my-editormd", { //注意1：这里的就是上面的DIV的id属性值
            width: "90%",
            height: 640,
            syncScrolling: "single",
            **path: "http://localhost:9090/ssm/assets/vendors/editormd/lib/", //注意2：你的路径
            pluginPath:"http://localhost:9090/ssm/assets/vendors/editormd/plugins/",**
            imageUpload : true,
            imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "/upload",
            saveHTMLToTextarea : true,
            saveHTMLToTextarea: true //注意3：这个配置，方便post提交表单
        });
    });
</script>

**Comment by zhenqicai** [comment]
@Tiakon   自定义插件也弄了，还是一样的！
<script type="text/javascript">
    $(function() {
        var editor = editormd("my-editormd", { //注意1：这里的就是上面的DIV的id属性值
            width: "90%",
            height: 640,
            syncScrolling: "single",
            path: "http://localhost:9090/blog-ssm/assets/vendors/editormd/lib/", //注意2：你的路径

            pluginPath:"http://localhost:9090/blog-ssm/assets/vendors/editormd/plugins/",
            imageUpload : true,
            imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "/upload",
            saveHTMLToTextarea : true,
            saveHTMLToTextarea: true //注意3：这个配置，方便post提交表单
        });
    });
</script>

**Comment by zhenqicai** [comment]
@Tiakon 自定义插件也弄了，还是一样的！
```
<script type="text/javascript">
    $(function() {
        var editor = editormd("my-editormd", { //注意1：这里的就是上面的DIV的id属性值
            width: "90%",
            height: 640,
            syncScrolling: "single",
            path: "http://localhost:9090/blog-ssm/assets/vendors/editormd/lib/", //注意2：你的路径

            pluginPath:"http://localhost:9090/blog-ssm/assets/vendors/editormd/plugins/",
            imageUpload : true,
            imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "/upload",
            saveHTMLToTextarea : true,

            saveHTMLToTextarea: true //注意3：这个配置，方便post提交表单

        });
    });
</script>
```

**Comment by Tiakon** [comment]
你把pluginPath和path写成相对路径试试，另外把image-dialog文件放到plugins文件夹下

**Comment by Tiakon** [comment]
@zhenqicai 你把pluginPath和path写成相对路径试试，另外把image-dialog文件放到plugins文件夹下

**Comment by zhenqicai** [comment]
java web  这个项目结构是这样的。
![3608](https://user-images.githubusercontent.com/20643420/33944113-1849b3c0-e056-11e7-9313-da0ba4122382.png)
![5341](https://user-images.githubusercontent.com/20643420/33944119-21a12bf6-e056-11e7-8287-ac0ae25b7be3.png)

**Comment by Tiakon** [comment]
如果是webapp下的文件要引用，那 path: "./assets/vendors/editormd/lib/"
pluginPath:"./assets/vendors/editormd/plugins/"
pluginPath应该可以不用写，你只要把从editor.md-master中的image-dialog放到你项目中的plugins,应该就可以了呀

**Comment by Tiakon** [comment]
@zhenqicai 如果是webapp下的文件要引用，那 path: "./assets/vendors/editormd/lib/"
pluginPath:"./assets/vendors/editormd/plugins/"
pluginPath应该可以不用写，你只要把从editor.md-master中的image-dialog放到你项目中的plugins,应该就可以了呀

**Comment by zZ-GitHub** [comment]
@zhenqicai 只说前端 你走通了么

**Comment by zhenqicai** [comment]
@zZ-GitHub 可能是路径问题吧！ 我在试试看！

**Comment by zhenqicai** [comment]
@zZ-GitHub  @Tiakon   还是。。。。这样！
![90421](https://user-images.githubusercontent.com/20643420/33989310-ff95fa80-e101-11e7-972b-35359ea37605.png)

**Comment by zZ-GitHub** [comment]
#495

**Comment by zhenqicai** [comment]
@Tiakon  @zZ-GitHub 谢谢你们，导致editormd插件无法加载进来，是我自己引入了第三方sea.js，而后将sea.js相关的js注释了就可以了！或许两者有些冲突吧！ #495
