### ISSUE TITLE
parse code  "<meta http-equiv="refresh" content="0;url=https://www.baidu.com/">  ",will go to this url?

### ISSUE THREAD

**Issue by dczxw** [pandao/editor.md#491]
Excuse, when I parse the code in the editor , the page will go to www.baidu.com !
```
<meta http-equiv="refresh" content="0;url=https://www.baidu.com/">
```
what can I do to solve this problem?

**Comment by pandao** [comment]
@dczxw disable `htmlDecode` option, 或者 filter HTML tags.

http://editor.md.ipandao.com/examples/html-tags-decode.html
