### ISSUE TITLE
基于你的开源项目,弄了个editor.md.app现在有些问题需要和你探讨.

### ISSUE THREAD

**Issue by llxwj** [pandao/editor.md#50]
我原来用Chrome Package App封装, 因为CSP的原因,image,js,css等都不能访问在线资源.但是封装成app的也是为了离线即可以使用,现在改用node-webkit封装后,就没有CSP的限制了.效果非常好.
所以我有如下的几个建议:
* 能否增加Tab的支持,有一个工具栏,可以操作多个markdown文件了.
* 能否增加一个选项,比如emoji表情,可以使用在线的,也可以使用离线的,就是在表情标记被解析为HTML的img 时src可以配置成在线绝对路径,或相对用户本地的一个目录.
* 同样markdonw中插入的图片,也可以用网络资源,也可以用本地资源.用本地资源,是相对于markdown文件的本地路径的.

**Comment by pandao** [comment]
谢谢你的建议，关于Tab是想到一块了。emoji图片地址可以自定义，图片也有支持本地的。

**Comment by llxwj** [comment]
能不能增加一个方法或属性,让用户动态的配置,是用本地的还是网络的?
```javascript
editormd.emoji     = {
        path  : "emoji-cheat-sheet.com/public/graphics/emojis/",
        ext   : ".png"
    };
```
我想说的是,能动态的控制这个path的值.

**Comment by pandao** [comment]
@llxwj 重新对`editormd.emoji`赋值就可以了。
