### ISSUE TITLE
能否通过html格式得到md格式文本

### ISSUE THREAD

**Issue by Acamy** [pandao/editor.md#501]
后端数据库只保存了html格式，在进行编辑时希望能通过html得到md文本，应该如何配置？

**Comment by zZ-GitHub** [comment]
提供的有吧

**Comment by Acamy** [comment]
楼上能否给一个example链接呀,谢谢

**Comment by zZ-GitHub** [comment]
看错了  为啥 不 保存  md

**Comment by Acamy** [comment]
当时没考虑到要用html转md.
现在添加嫌麻烦了，理论上应该能通过html转md才对呀
如果数据库里同时保存html和md是否太庸余了？

**Comment by zZ-GitHub** [comment]
是冗余了  所以 只 保存 md 的 好了

**Comment by zZ-GitHub** [comment]
你说的这种 网上是有的 但是 效果不是很好就是了  很对东西 好像不支持

**Comment by Acamy** [comment]
如果只保存md的话，在浏览时怎么转换为html呀
是用下面这个配置吗？我试了但好像没效果
> <script type="text/javascript">
    editormd.markdownToHTML("content",{
          htmlDecode      : "style,script,iframe",  // you can filter tags decode
            emoji           : true,
            taskList        : true,
            tex             : true,  // 默认不解析
            flowChart       : true,  // 默认不解析
            sequenceDiagram : true,  // 默认不解析
        });

**Comment by zZ-GitHub** [comment]
有例子好像

**Comment by hawtim** [comment]
var editor = editormd(id, options)
editor.getMarkdown()

**Comment by pandao** [comment]
@Acamy 目前不支持，你可以找一下其他 HTML 转 Markdown 的库，建议保存 Markdown 源码到数据库。
