### ISSUE TITLE
可以配置成普通的富文本编辑器吗？

### ISSUE THREAD

**Issue by lgxkdream** [pandao/editor.md#505]
可以去掉预览功能，变成普通的富文本编辑器吗？

**Comment by pandao** [comment]
@lgxkdream 可以关闭预览，但不能变成传统的 HTML 可视化编辑器。

**Comment by hawtim** [comment]
@lgxkdream 你可以在htmlDecode 选项中过滤掉某些标签，那样的话是可以编辑和预览富文本，只不过前提是要看得懂HTML
