### ISSUE TITLE
关于图片地址或者超链接解析的一个bug

### ISSUE THREAD

**Issue by hainuo** [pandao/editor.md#51]
![image](https://cloud.githubusercontent.com/assets/421861/6680964/f4d75b22-cc99-11e4-8fb4-0ee853b42a80.png)
图片1的连接 后面带着-1@2x 在进行url解析时主动讲这个给过滤掉了，

**Comment by pandao** [comment]
嗯，已标记。

**Comment by pandao** [comment]
@v1.4.0 fixed.
