### ISSUE TITLE
能不能加个“隐藏编辑器”选项

### ISSUE THREAD

**Issue by kcloze** [pandao/editor.md#52]
只读模式下，希望能把左边的编辑框隐藏掉，只看到编辑后的内容

**Comment by pandao** [comment]
{ watch : false }

**Comment by kcloze** [comment]
![hide](https://cloud.githubusercontent.com/assets/1489176/6727327/0850f5fa-ce5c-11e4-8ae2-c43f54f40cc3.png)
想让编辑器隐藏，而不是禁用实时预览

**Comment by llxwj** [comment]
```javascript 
$("#hide-btn").bind('click', function(){
    testEditor.hide();
});
```
testEditor 你创建的编辑器对象.
https://pandao.github.io/editor.md/examples/full.html 有例子!

**Comment by kcloze** [comment]
```
testEditor.hide();
```
 这样的话，右边的显示区域都隐藏了

**Comment by pandao** [comment]
@kcloze 

```javascript
{
    onload : function(){
        this.previewing();
    }
}
```

如果只是解析和显示Markdown，请参考[https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html](https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html)

**Comment by wufeng87** [comment]
但是，调用了下面这个接口 后，就没有setMarkdown方法可以调用了，感觉还是有点不方便。解析和显示模式下，应该也能用setMarkdown才好：
testEditormdView = editormd.markdownToHTML

**Comment by ym13349140** [comment]
同感，直接调用markdownToHTML预览的话，就无法获取markdownTOC数组，也无法调用一系列的editor方法了；在编辑态下又没有办法隐藏编辑框。不知道markdownToHTML模式下有没有可能支持完整的setMarkdown等方法和markdownTOC等属性呢？
