### ISSUE TITLE
求图片的粘贴上传功能

### ISSUE THREAD

**Issue by swimmingwhale** [pandao/editor.md#524]
每次截图都要先报存再上传,真的很麻烦.
看了半天好像源码,好像是codemirror没有开放paste事件,自己实在搞不定了,求大神写一个粘贴直接上传图片的功能

**Comment by terranc** [comment]
同感，不知有无计划？

**Comment by rockmelodies** [comment]
成功了吗？粘贴图片

**Comment by pandao** [comment]
Duplicate of #219
