### ISSUE TITLE
如何获取解析html之后的MD源码（不是解析后的html）？

### ISSUE THREAD

**Issue by YounianC** [pandao/editor.md#528]
* 在开启了html解析之后，在左边输入html代码，右边显示解析效果
* 这个时候
  * 调用`testEditor.getMarkdown()`得到的是我左边输入的html代码；
  * 调用`testEditor.getHTML()`获取的是右边解析过后的**HTML代码**。

有函数能获取解析过后的MD源码吗？

**Comment by lxb563859671** [comment]
@fifsky 

> [__]([url]([url]([url]([url]([url]([url]([url]([url]([url](

> url

))))))))))

**Comment by pandao** [comment]
@YounianC 没有。
