### ISSUE TITLE
autoHeight(自动高度)在preview下内容会消失

### ISSUE THREAD

**Issue by lixplor** [pandao/editor.md#531]
autoHeight(自动高度)在preview下内容会消失
示例页面(https://pandao.github.io/editor.md/examples/auto-height.html)也有这种问题, 当点击preview按钮后, 主题内容高度为0, 内容消失不见了

**Comment by AnonymousArthur** [comment]
@liangyd1024 @lixplor 这包已经凉了，2015之后就没有更新了

**Comment by liangyd1024** [comment]
@AnonymousArthur 那这个问题就没法解决了么？

**Comment by AnonymousArthur** [comment]
@liangyd1024 这个包没在维护了。
看一下这个别人fork过去改的能不能帮助你， 原Issue #545 仓库地址: https://github.com/hawtim/editor.md/blob/master/CHANGE.md

**Comment by pandao** [comment]
Duplicate of #140
