### ISSUE TITLE
github emoji 加载失败，无法显示

### ISSUE THREAD

**Issue by 54lxb** [pandao/editor.md#536]
已找到原因，是路径问题；
在editormd.js文件中的第3368行：
`editormd.emoji     = {
        path  : "http://www.emoji-cheat-sheet.com/graphics/emojis/",
        ext   : ".png"
    };`
修改path为 `https://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/`
然后重新压缩js即可；

**Comment by CS2JOONGKI** [comment]
你好.试了你的方法,还是不行啊

**Comment by 54lxb** [comment]
可以的哦，我的改了就可以了；
没改之前如图：
![c rse 4jxv8p61m4pji4 8](https://user-images.githubusercontent.com/20807974/36978911-c454abac-20c0-11e8-8640-e8f54761808e.png)

改过之后如图：
![shpebxfh2 cv84 qfc4 7j](https://user-images.githubusercontent.com/20807974/36979045-3851e682-20c1-11e8-94a2-4ec86a7f455a.png)

**Comment by pandao** [comment]
Duplicate of #300
