### ISSUE TITLE
是否不支持IE9

### ISSUE THREAD

**Issue by fifsky** [pandao/editor.md#54]
编写玩文档之后，使用转HTML显示方式，发现IE9会打不开页面，比如
https://pandao.github.io/editor.md/examples/html-preview-markdown-to-html.html  

会跳转到
res://ieframe.dll/acr_error.htm#github.io,https://pandao.github.io/editor.md/examples/sequence-diagram.html

**Comment by pandao** [comment]
@fifsky 支持IE8及以上版本。经测试未出现你所说的情况。

**Comment by chwmqq** [comment]
和我遇到的问题一样 IE9会崩溃
