### ISSUE TITLE
在我的仓库发布了新版本/ new version in my fork repository

### ISSUE THREAD

**Issue by hawtim** [pandao/editor.md#545]
修复了部分bug，升级了项目构建工具，不兼容 IE9 以下
项目地址：
https://github.com/hawtim/editor.md

:bug: 修复使用 on* 过滤标签的属性，图片加链接的语法会出错的问题
:bug: 修复<0000>的文本会被识别成标签的问题处理
:zap: 编辑器使用自动高度时，可以设置编辑器的最小高度和最大高度
:bug: 修复关闭同步滚动后输入内容右侧不更新的问题及输入内容右侧滚动条跳转的问题

构建工具使用 babel 转换后再进行 uglify，原本会在 uglify 时报错，因不支持对象动态属性，例如：

```js
var key = 'Ctrl'
keyMap = {
    [key + '-1']: 'h1'
}
```
故转换后使用了 Object.defineProperty() 来支持对象动态属性，所以不支持 IE9 以下
欢迎 star & fork & issue

**Comment by hawtim** [comment]
TODOs:
1. 增加链接为新页面打开的配置项
2. 处理上传图片接受的文件类型
3. 增加粘贴图片上传功能 #524/#519
4. 点击事件判断错误 #526
5. 有序列表解析问题 #543
6. 最新分支无法通过gulp正常生成 #513 finish

**Comment by hawtim** [comment]
### v2.0.1

- 新增： 增加 TODO 文件，欢迎大家来此提需求/ update TODO file, welcome your issues

- 改进： 修复 toc 列表节点标识错误的问题 / fixed toc list have a wrong sign
- 改进： 更新 marked 的版本用以修复有序列表初始序号错误的问题 / update markded.js to fix order list got a wrong start number #543
- 改进： 修复 on* 过滤条件下，`<a href="javascript:alert('xss')">xss</a>` 会引发 XSS 的问题 / fixed xss problem

**Comment by ye21st** [comment]
@hawtim 支持。希望能建一个群一起交流，学习。

**Comment by AlmogRnD** [comment]
Is this is the new version that we should be using? How can I get both markdown the html would like to save both in my db?

**Comment by wujianglong** [comment]
想了解下  关于英文引号  总是转义成中文引号

**Comment by wufeng87** [comment]
增加粘贴图片上传功能   请问这个任务项怎么样了？没弄好的话，有思路吗？我也想试试加上这个功能。

**Comment by ElderJames** [comment]
支持，希望作者 @pandao 可以给下管理权限，让这个项目继续下去。我也想做一下Angular的支持

**Comment by Zephery** [comment]
hello。。。。请问图片那个怎么样 了？

**Comment by zhangruinian** [comment]
感觉同步滚动一直不好用呀,左侧存在流程图和图片的时候,右侧滚动精度不行

**Comment by rockmelodies** [comment]
请问粘贴图片可以了吗？

**Comment by rockmelodies** [comment]
@hawtim 可以粘贴吗

**Comment by ElderJames** [comment]
能否完全复制到独立仓库，让其他人的pr可以合并起来？
