### ISSUE TITLE
2年没更新了。。

### ISSUE THREAD

**Issue by Cinux-Chosan** [pandao/editor.md#549]

**Comment by Cinux-Chosan** [comment]
作者微博 、twitter、 github 都两三年没更新了 ，还有那个 http://www.ipandao.com/ 的网页也打不开了。。

**Comment by Ray-Eldath** [comment]
同问啊... 是不是弃坑了
不知道不再维护的玩意搁到生产环境里会不会出问题╮(￣▽￣")╭

**Comment by Ray-Eldath** [comment]
@terranc 不清楚啊... 我也找了几圈了...
目前感觉[tui.editor](https://github.com/nhnent/tui.editor)不错 但是自定义**太不方便** 就连自定义工具栏的demo都没有=_=
可能还是只能用这个库吧... 但是毕竟已经没有维护了 目前我用的就是tui.editor 只能凑合着了(╯︵╰,)

**Comment by zZ-GitHub** [comment]
@Ray-Eldath 正在准备入坑 [tui.editor](https://github.com/nhnent/tui.editor) ，你感觉 tui.editor 好用么

**Comment by Ray-Eldath** [comment]
@zZ-GitHub 还行吧...该有的功能都有
但是中规中矩 而且自定义性不强 至少从文档上来说
然而对我来说自定义性太重要了...

**Comment by zZ-GitHub** [comment]
@Ray-Eldath 我能力不强  但是 这个看源码 应该都可以配置的吧  最麻烦的 直接改源代码 不就得了

**Comment by Ray-Eldath** [comment]
@zZ-GitHub 不知道嘞 要是这么简单就好了
不过我还是希望它能提供一个demo...
---
话说我给本仓库的作者发了封邮件 不知道它收不收得到...
好像作者的新浪微博**又开始**活跃了？

**Comment by zZ-GitHub** [comment]
@Ray-Eldath 我在issue 的时候见过作者，估计忙的不行，说有空了可能更新

**Comment by pandao** [comment]
Duplicate of #215
