### ISSUE TITLE
How to translate the code dialog placeholder to another language

### ISSUE THREAD

**Issue by Astak** [pandao/editor.md#555]
I created the languages/en.js copy and changed all labels as required. I also added the preformattedText and codeBlock sections copied from corresponding plugin files to translate labels in the corresponding dialog windows. However, I could not find how to translate the placeholder text demonstrated in the screenshot.
<img width="768" alt="screen shot 2018-04-01 at 21 55 13" src="https://user-images.githubusercontent.com/4731868/38176482-734a769a-35f8-11e8-84ed-135daaca7f5a.png">

**Comment by hawtim** [comment]
you can find the placeholder of the codeBlock section in `code-block-dialog.js` Line 88

**Comment by 1455066227** [comment]
https://pandao.github.io/editor.md/examples/multi-languages.html

**Comment by pandao** [comment]
#556
