### ISSUE TITLE
怎么给编辑器赋值？

### ISSUE THREAD

**Issue by MrXiaoYe** [pandao/editor.md#557]
怎么给编辑器赋值？

**Comment by imkgg** [comment]
editor.setMarkdown(contents);

**Comment by wenjianhua-isoon** [comment]
就是这个方法，但是注意插件的加载的先后顺序

**Comment by pandao** [comment]
@MrXiaoYe 使用配置项 `markdown` 或者调用 `setMarkdown(markdown)` 方法。
