### ISSUE TITLE
emojio加载异常

### ISSUE THREAD

**Issue by Easoncheng0405** [pandao/editor.md#567]
* github emoji无法加载
* 选择emoji需要点击确定才能显示到文本里
* 多次点击emoji会出现多个emoji点击确定后全部出现在文本里(没有预览)

**Comment by HullQin** [comment]
@Easoncheng0405 这里的url是需要翻墙的。如果不想用户翻墙，可以把那些emoji下载到本地的static的某个位置，改上面图中path为自己的文件夹位置即可。详见这篇我在网上搜到的教程：https://www.jianshu.com/p/9670fe7a8c32

**Comment by pandao** [comment]
Duplicate of #300
