### ISSUE TITLE
不符合md语法的写法，也会成功预览为表格

### ISSUE THREAD

**Issue by tjsky** [pandao/editor.md#568]
这种不符合md语法的写法，也会成功预览为表格
到了文章页就不转化为表格
![default](https://user-images.githubusercontent.com/7272911/39391229-da1b334a-4a8f-11e8-82d5-81a3272a968f.png)

**Comment by hawtim** [comment]
@tjsky 我在我实际项目中试着写了你的提供的 markdown 表格，没有发现文章页不转化为表格的问题。
并且我看你的写法是符合md语法的，如果你方便的话可以提供对应的demo

**Comment by HullQin** [comment]
@tjsky 看了你提供的demo，发现是你短横线格式不对所致。你网页里面写的是全角符号的"—"而非英文符号“-”。已测试，改正后可以显示。
