### ISSUE TITLE
How to set up preview mode 

### ISSUE THREAD

**Issue by AlmogRnD** [pandao/editor.md#573]
How can I set up just a preview mode or render/read-only mode?

**Comment by Chrisphyz** [comment]
Here is the doc: [](https://pandao.github.io/editor.md/examples/readonly.html)
For more infomation: [](https://pandao.github.io/editor.md/en.html)

**Comment by AlmogRnD** [comment]
Thanks got it working

**Comment by prayatna** [comment]
can we setup the preview to be at the bottom of the editor?
