### ISSUE TITLE
求解如何自动触发全屏模式?

### ISSUE THREAD

**Issue by akar1nchan** [pandao/editor.md#59]
https://github.com/pandao/editor.md/blob/master/examples/full.html

很不错的编辑器呢

**Comment by pandao** [comment]
@akar1nchan 参考示例 [https://pandao.github.io/editor.md/examples/manually-load-modules.html](https://pandao.github.io/editor.md/examples/manually-load-modules.html)

**Comment by akar1nchan** [comment]
THX～
