### ISSUE TITLE
Why another online markdown editor?

### ISSUE THREAD

**Issue by CatTail** [pandao/editor.md#6]

**Comment by pandao** [comment]
??? Becouse I can't found online markdown editor for  my needing. So...

**Comment by CatTail** [comment]
How about this? http://maxiang.info/. Through, I don't use it at all.

Try to search google enough before you make anything.

**Comment by pandao** [comment]
@CatTail  No, that's not what I wanted.

**Comment by CatTail** [comment]
What do you want? What's the difference?

**Comment by pandao** [comment]
I need one markdown editor for back-end, the open source markdown editor, Like the html editor.
