### ISSUE TITLE
能不能出个精简版本。。。编辑器确实很强大。不过太多的依赖加载项有些人不需要啊。

### ISSUE THREAD

**Issue by 9v-kz** [pandao/editor.md#60]
这编辑器对写博客的人功能确实不错。对于多用户系统的有些功能可以更精简一点。比如流程图，raphael.js那些的，[TOC]目录之类的。 
如果这些可以去掉那就太好了。
Rephael.js
flowchart.js
sequence-diagram.js 
仅支持md传统语句格式的。当然这是我个人建议。
编辑器的工具栏自定义的么？
最后表示这编辑器的确很强大。

**Comment by pandao** [comment]
@9v-kz 流程图默认是不开启的，这样就不用加载相关的模块了，你完全可以自己根据需要来配置的，是否开启流程图或者TOC等增强功能。

**Comment by 9v-kz** [comment]
@pandao 是这样啊。你的编辑器项目必须得加星。谢谢。

**Comment by pandao** [comment]
@9v-kz 更多Editor.md 自定义示例 [https://pandao.github.io/editor.md/examples/index.html](https://pandao.github.io/editor.md/examples/index.html)
