### ISSUE TITLE
同一个页面如果有2个初始化options不一样的editor，第一个初始化的options会被后面初始化的覆盖掉

### ISSUE THREAD

**Issue by wufeng87** [pandao/editor.md#600]
![image](https://user-images.githubusercontent.com/1686808/42915089-599c3dea-8b30-11e8-8873-832148a4ec81.png)

如图，上面那个开启了实时预览；下面的是后初始化的，下面的没开启实时预览。拖拽resize上面那个编辑器时，其实时预览属性会被覆盖成false，然后预览消失。

谢谢。

**Comment by pandao** [comment]
Duplicate of #218
