### ISSUE TITLE
请教一下这path属性的路径到底怎么设置的，弄了半天也没弄出来，谢谢

### ISSUE THREAD

**Issue by 9v-kz** [pandao/editor.md#61]
今天想更换网站的编辑器，可是怎么也设置不了path。。。。

**Comment by 9v-kz** [comment]
编辑器全部的文件都放到了localhost/site/static 目录下

**Comment by pandao** [comment]
在使用默认的自动加载依赖模块模式下，path配置项是用来指定加载Editor.md依赖模块的路径，即`./lib/`目录。如果不使用默认的，需要参考`./lib/`的文件结构。

**Comment by 9v-kz** [comment]
@pandao 谢谢。哈哈，刚才搞错了，设置路径没错。我还以为设置编辑器的时候要赋给textarea的id呢。。。原来是外面div的id...example里面的还真没注意看。。。。呵呵。。。不好意思。
