### ISSUE TITLE
editor.md是否有将markdown内容加载到编辑区域的功能？

### ISSUE THREAD

**Issue by quietin** [pandao/editor.md#63]
想通过编辑器加载markdown内容，在网站上看了半天，没看到有相关的函数，用jquery将内容塞到.CodeMirror-code下，内容能显示。。但是没有预览效果
请问目前是否有加载md内容到编辑区并且自动预览的功能呢？

**Comment by pandao** [comment]
@quietin 可以使用`setMarkdown()`或者`setValue()`方法，`appendMarkdown()`则是追加Markdown内容到编辑器。
