### ISSUE TITLE
KaTeX中一些符号无法显示

### ISSUE THREAD

**Issue by wormful** [pandao/editor.md#64]
不知道如何在KaTeX公式中显示`<`、`$`这些字符。在KaTeX中`<`可以直接显示，dollar符通过`\$`也可以显示。

`&`、`^`这种在KaTeX中我本来就不知道怎么显示，如果有方法也请告诉我。

**Comment by pandao** [comment]
@wormful 参考资料[http://meta.wikimedia.org/wiki/Help:Displaying_a_formula](http://meta.wikimedia.org/wiki/Help:Displaying_a_formula)

**Comment by wormful** [comment]
@pandao 但是KaTeX对于TeX的实现很少。单字符的话`\&`这个就不支持，另外很多排版方式也不支持。这个是KaTeX的问题。

但是像小于号、大于号，在KaTeX中能且只能通过`<`和`>`显示，在editor.md里的公式中不清楚被忽略了还是转义了，用不了……

**Comment by pandao** [comment]
嗯，小于号、大于号等是有转义问题，变成HTML字体字符了，稍后修正。不支持的部分，只能等待KaTeX更新了。

**Comment by pandao** [comment]
@v1.4.1 fixed.
