### ISSUE TITLE
是否应该另外建一个仓库继续维护此项目？

### ISSUE THREAD

**Issue by ElderJames** [pandao/editor.md#648]
目前看来，作者不再维护此项目了，遗留了很多issue和pr未解决。
但是这个优秀的项目应该要让他发展下去，所以我们另外建个库或者组织来维护吧？

**Comment by HibernantBear** [comment]
我觉得如果有人继续维护是件好事呢，很优秀的项目，不过看了一下最近的提交时间。。。哈，毕竟开源嘛坐着也不一定总是那么闲啊
