### ISSUE TITLE
代码块不转义 < 和 >

### ISSUE THREAD

**Issue by meinqy** [pandao/editor.md#65]
插入代码块时，符号 < 和 > 不会被转义，页面输出的时候就会直接当标签解析。比如插入php代码

  <?php
  use Meinqy\Test;

其中开始 的 < 标签并不会被转移。 不知道有木有什么解决的办法

**Comment by pandao** [comment]
不会啊？能说一下具体的场景吗？

**Comment by meinqy** [comment]
哦，已找到问题原因，

因为使用 textarea 保存编译后的文本 所以 个人感觉应该使用 val() 而非 html() ，

this.htmlTextarea.html(newMarkdownDoc);

应改为

this.htmlTextarea.val(newMarkdownDoc);

 因为我对代码改动的地方太多（主要是增加功能适应项目） = =， 就不 push 了， 你看看是否需要在项目中做更改。

另外 感谢回复，感谢这个项目，确实省了不少力气，谢谢

**Comment by pandao** [comment]
你是直接修改源码?

**Comment by meinqy** [comment]
嗯， 不少东西不动源码没法适应项目，比如 项目上传图片的post需要在表单中添加 csrfToken，另外一些小功能按钮，比如插入一个 '摘要' 标记符 功能 就偷懒直接改源码，像这种为了适应项目的改动很多，所以就直接改了，源码改动不小，所以没有 push ，
