### ISSUE TITLE
[PR] 是否可以根据MD文档里面的标题生成概要的标题信息

### ISSUE THREAD

**Issue by a854363956** [pandao/editor.md#652]
是否可以根据文档的标题信息生成可以快速点击的标题信息,这边可以方便用户快速预览

**Comment by pandao** [comment]
@a854363956 你想说生成目录列表？

**Comment by jhoneybee** [comment]
> @a854363956 你想说生成目录列表？

对,是的根据标题生成目录列表

**Comment by pandao** [comment]
@jhoneybee 设置配置项 `toc` 为 `true`，然后在 Markdown 文档中写入 `[TOC]` 就可以自动生成目录列表了，示例：http://editor.md.ipandao.com/examples/toc.html
