### ISSUE TITLE
image-dialog 插件不支持带参数的上传地址

### ISSUE THREAD

**Issue by coolhpy** [pandao/editor.md#66]
`image-dialog.js` 第37行，原代码：
`var action = settings.imageUploadURL + "?guid=" + guid;`
要再加个判断，如下：
`var action = settings.imageUploadURL + (settings.imageUploadURL.indexOf('?') >= 0 ? "&" : "?") + "guid=" + guid;`

**Comment by pandao** [comment]
嗯，已标记，稍后修正，谢谢你的指正。

**Comment by pandao** [comment]
@v1.4.1 fixed.
