### ISSUE TITLE
有序列表解析异常

### ISSUE THREAD

**Issue by FantasticPan** [pandao/editor.md#668]
编辑时序号正常正常，转换成html后序号消失
![TIM截图20190410141227](https://user-images.githubusercontent.com/31149106/55855922-5ffd3900-5b9b-11e9-87c8-07a6aed33e16.png)
![TIM截图20190410141347](https://user-images.githubusercontent.com/31149106/55855924-62f82980-5b9b-11e9-8b53-0f50c0d42357.png)

**Comment by pandao** [comment]
@FantasticPan 你的列表序号没有按顺序，就是这样解析的，要遵循 Markdown 的语法。

**Comment by FantasticPan** [comment]
但是在右边的预览框中是有序号的，而且就算我编辑框中按顺序，保存之后的内容是没有序号的，只有文字内容

**Comment by FantasticPan** [comment]
@pandao 但是在右边的预览框中是有序号的，而且就算我编辑框中按顺序，保存到数据库之后的内容是没有序号的，只有文字内容
