### ISSUE TITLE
能够自动生成文章的目录吗？

### ISSUE THREAD

**Issue by JayCJP** [pandao/editor.md#672]
能够自动生成文章的目录吗？
Can this library automatically generate a catalog of articles?

希望可以提供一个根据标题生成目录树的功能 ^_^
就像 a 锚点 那样，点击可以快速定位。

**Comment by songyang1995** [comment]
[TOC] 好像能解决你的问题

**Comment by JayCJP** [comment]
> [TOC] 好像能解决你的问题

是呀，谢谢回答，在API中找到了这个，
http://pandao.github.io/editor.md/examples/toc.html
