### ISSUE TITLE
建议在下个版本增加对齐语法

### ISSUE THREAD

**Issue by cnspray** [pandao/editor.md#677]
作者你好，建议在下个版本增加对齐语法，-:,:-::-左对齐，居中对齐，右对齐。

**Comment by pandao** [comment]
@cnspray 你说的是表格行的对齐，这个有支持呀。

**Comment by cnspray** [comment]
我指的是正文和图片的，就像看云使用的编辑器那样。

**Comment by cnspray** [comment]
@pandao
目前段落图片对齐的实现只有通过开启html解析，很不方便，对齐这个功能在编辑文档的时候，使用率还是挺高的。https://www.kancloud.cn/

**Comment by pandao** [comment]
@cnspray 你所说这些语法属于 Kancloud 自己扩展的语法，非 Markdown 标准语法，暂时不考虑。
