### ISSUE TITLE
toolbar是否考虑添加类似segmentfault md编辑器的右对齐功能

### ISSUE THREAD

**Issue by xiegang** [pandao/editor.md#69]
![segmentfault md toolbar](http://i.imgur.com/lxHTh4I.png)

**Comment by pandao** [comment]
?

**Comment by xiegang** [comment]
上次提交截图没成功

**Comment by pandao** [comment]
@xiegang 那个不是右对齐吧，那个是全窗口编辑和预览的切换。

**Comment by xiegang** [comment]
@pandao 可能我没描述清楚，我的意思就是工具栏的图标通过配置能不能一部分放到右边^_^

**Comment by pandao** [comment]
@xiegang 暂时没有直接的配置方法，你可以通过jQuery来操作DOM，结合Editor.md的Api方法。

**Comment by pandao** [comment]
@xiegang @v1.4.2 已支持工具栏图标按钮的右对齐方式。
