### ISSUE TITLE
代码块问题

### ISSUE THREAD

**Issue by ChinaDragonNB** [pandao/editor.md#691]
代码块中的中文是繁体字，怎么改成中文简体？

**Comment by fengxueguang** [comment]
我们也遇到这个问题了，但是不是所有的都会有这个问题。
请问你最后是怎么解决的呢？

**Comment by ChinaDragonNB** [comment]
需要把字体换一下

**Comment by ChinaDragonNB** [comment]
> 我们也遇到这个问题了，但是不是所有的都会有这个问题。
> 请问你最后是怎么解决的呢？

需要把字体换一下

**Comment by fengxueguang** [comment]
谢谢，是客户端使用的字体吗？

**Comment by ChinaDragonNB** [comment]
> 谢谢，是客户端使用的�字体吗？

我是把它引用的css里面的字体换就不会有繁体字了，

**Comment by fengxueguang** [comment]
好的多谢
