### ISSUE TITLE
建议给出HTML禁止或允许使用的标签设置，是否允许JS等设置

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#70]
很不错的工作。
个人建议增加禁止或者允许某些HTML标签的设置。让使用者自己去配置。
还有不应该禁止掉JS吗？

**Comment by pandao** [comment]
过滤指定HTML标签解析示例：

```javascript
{
    htmlDecode : "style,script,iframe" // 指定你想禁止解析的HTML标签
    // htmlDecode : true                      // 开启 / 解析所有HTML标签
    // htmlDecode : false                     // 禁用HTML标签解析
}
```

[https://pandao.github.io/editor.md/examples/html-tags-decode.html](https://pandao.github.io/editor.md/examples/html-tags-decode.html)

**Comment by wakaryry** [comment]
我明白你的意思了
https://pandao.github.io/editor.md/examples/full.html
我想你应该还要禁止掉一些属性和事件
不然htmlDecode : "style,script,iframe"并不会满足要求
‘’‘HTML
<p style="color:red;text-align:center;border:3px solid #000;height:30px;line-height:24px;" onclick="javascript:alert('hi');">nihao ya </p>
<i class="fa fa-circle"></i>
<style>body{background:red;}</style>
’‘’

**Comment by pandao** [comment]
@wakaryry 嗯，谢谢你的建议，尤其是关于禁止事件。

**Comment by wakaryry** [comment]
非常不错的东西
迫不及待等着使用

**Comment by pandao** [comment]
@wakaryry @v1.4.2 已支持过滤属性和事件。

**Comment by wakaryry** [comment]
@pandao Nice

**Comment by 9v-kz** [comment]
这里禁止html标签指的是预览部分html标签么？还是提交表单的时候markdown内容和会被过滤么？

**Comment by pandao** [comment]
@9v-kz 是指解析和预览的HTML的标签及属性。
