### ISSUE TITLE
是否提供@时触发某些动作的接口？

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#73]
因为@某个人很常用。而目前好像就只可以设置@的baseURL。貌似不能满足要求，比如说@的时候能够调用ajax，然后返回自己当前的朋友的名字，或者@的时候可以返回当前页面中的参与者。好比github的这个编辑器一样，@很智能，也很方便。

**Comment by pandao** [comment]
@wakaryry 很好的提议，可以研究一下，看看能不能实现。

**Comment by wakaryry** [comment]
@pandao 
http://simditor.tower.im/extension.html

**Comment by 9v-kz** [comment]
这个建议非常不错
