### ISSUE TITLE
问一下怎么取消光标自动对焦编辑器上？

### ISSUE THREAD

**Issue by 9v-kz** [pandao/editor.md#74]

**Comment by pandao** [comment]
@9v-kz 没有办法，除非是只读模式。

**Comment by 9v-kz** [comment]
@pandao 哦，那希望下一个版本改善一下，拜托了，网站是多用户系统，每次打开内容内页光标都在编辑器上 感觉就像强迫用户提交评论一样，很不友好。

**Comment by pandao** [comment]
@9v-kz 找到一个临时解决方案，打开 editormd.js，修改如下：

	# 在 108行（即 autoCloseTags : true,） 前面加一行
	autoFoucs : true,

	找到 620 行将 autofocus : true, 修改为 autofocus : settings.autoFoucs,

然后配置：

	# 新版本可以通过这样取消自动 focus
	var editor = editormd('xxxx', {
		autoFoucs : false
	});

**Comment by pandao** [comment]
@9v-kz @jimmykuu fixed @v1.4.3 .

**Comment by 9v-kz** [comment]
@pandao 谢谢

**Comment by forecho** [comment]
> @9v-kz 找到一个临时解决方案，打开 editormd.js，修改如下：
> 
> ```
> # 在 108行（即 autoCloseTags : true,） 前面加一行
> autoFoucs : true,
> 
> 找到 620 行将 autofocus : true, 修改为 autofocus : settings.autoFoucs,
> ```
> 然后配置：
> 
> ```
> # 新版本可以通过这样取消自动 focus
> var editor = editormd('xxxx', {
>     autoFoucs : false
> });
> ```

写错了吧？应该是：

```
# 新版本可以通过这样取消自动 focus
var editor = editormd('xxxx', {
    autoFocus : false
});
```
