### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by sofu456** [pandao/editor.md#745]
i use react to integrate editor.md ，just only import the editormd.js，find the browser donnot get the files in the subpath of lib，so html come with 

TypeError: Cannot read property 'fromTextArea' of null

so the project maybe miss the index.js file that contain all the editor.md js file.

**Comment by wangzhijun-github** [comment]
How do you fixed

**Comment by sofu456** [comment]
markdown editor is compile by gulp, the compack is not for modules,you need a webpack project . and then import one not gulp project

**Comment by sofu456** [comment]
> How do you fixed

markdown editor is compile by gulp, the compack is not for modules,you need a webpack project . and then import one not gulp project
