### ISSUE TITLE
一个bug：使用editormd.markdownToHTML时，当传入的markdown为数字时，会报错

### ISSUE THREAD

**Issue by giantray** [pandao/editor.md#77]
一个bug：使用editormd.markdownToHTML时，当传入的markdown参数为数字时，会报错

解决办法，强制将参数转为string

**Comment by pandao** [comment]
@giantray 嗯，已标记，稍后一并更新。

**Comment by pandao** [comment]
@giantray fixed @v1.4.3 .

**Comment by toxicyu** [comment]
@giantray 我在用editormd.markdownToHTML的时候报marked undefined错误，然后把marked.min.js引用后问题解决，但是又出codemirror错误，不知道您实现的时候有没有遇到过这个问题？
