### ISSUE TITLE
建议加个 autofocus 的 option

### ISSUE THREAD

**Issue by jimmykuu** [pandao/editor.md#78]
默认 `codeMirrorConfig` 的 `autofocus` 为 `true`，导致页面加载后自动 focus 编辑器，如果编辑框在最底部的话，会页面会滚动到最底部。

PS： 在 http://golangtc.com 用上 editor.md 了。

**Comment by jimmykuu** [comment]
没注意 #74 有人已经提了。

**Comment by pandao** [comment]
@jimmykuu 嗯，下个小版本会加上，暂时还请先自行修改源码。感谢 [http://golangtc.com ](http://golangtc.com) 采用 Editor.md。
