### ISSUE TITLE
关于帮助对话框里的链接

### ISSUE THREAD

**Issue by jimmykuu** [pandao/editor.md#79]
在编辑状态下，打开帮助对话框，点一下里面的连接，直接跳转了，再后退回来，前面编辑的内容没了。

建议帮助对话框里的连接都加上 `target="_blank"` 。

**Comment by pandao** [comment]
@jimmykuu 嗯，谢谢你的提议。由于 Markdown 没有  `target="_blank"` 这样的语法，只能通过 jQuery 来操作 `<a>` 的 `target` 属性，稍后更新。

**Comment by pandao** [comment]
@jimmykuu fixed @v1.4.3 .

**Comment by akof1314** [comment]
`·markedRenderer.atLink`和`markedRenderer.link`是否也加`target=\"_blank\" `这样不小心点到右边链接的时候，不会在本页面跳转呢

**Comment by pandao** [comment]
@akof1314 嗯，可以考虑一下，在编辑状态也是很有必要这样。
