### ISSUE TITLE
添加图片有两个地址

### ISSUE THREAD

**Issue by sunhao-java** [pandao/editor.md#8]
添加图片时有两个框，不知道有什么区别？
![qq 20150215225102](https://cloud.githubusercontent.com/assets/2178487/6203624/383532d2-b565-11e4-8579-21225b4cba60.png)
而且按钮好像不大对啊，`地址`和`链接`不是一个吗？

**Comment by pandao** [comment]
1、图片地址是图片源文件地址；
2、链接是目标URL链接。

第三个我刚传上来，正在改介绍页面。

**Comment by sunhao-java** [comment]
嘿嘿 太关注你这个了
