### ISSUE TITLE
How can I use in angular8+ ?

### ISSUE THREAD

**Issue by calraiden** [pandao/editor.md#802]
Hi, can I use in angular8+ with typescript?

I didn't find any example

**Comment by HectorJiang** [comment]
> Hi, can I use in angular8+ with typescript?
> 
> I didn't find any example

This repository is out of date,it has many bugs，

Maybe you can find  another solution or fix this repository .And I'm also finding.:smile:

**Comment by calraiden** [comment]
> 
> 
> > Hi, can I use in angular8+ with typescript?
> > I didn't find any example
> 
> This repository is out of date,it has many bugs，
> 
> Maybe you can find another solution or fix this repository .And I'm also finding.😄

Really?  :sob: 

Thank you for reply :grinning:

**Comment by HectorJiang** [comment]
> > > Hi, can I use in angular8+ with typescript?
> > > I didn't find any example
> > 
> > 
> > This repository is out of date,it has many bugs，
> > Maybe you can find another solution or fix this repository .And I'm also finding.😄
> 
> Really? 😭
> 
> Thank you for reply 😀

Maybe you can try this:
https://github.com/Vanessa219/vditor

support javascript
