### ISSUE TITLE
:+1: emoji 支持不完整 

### ISSUE THREAD

**Issue by overtrue** [pandao/editor.md#81]
:+1: `:+1`不支持
:-1:  `:-1`是OK的

**Comment by pandao** [comment]
@overtrue 嗯，已标记，稍后一并修复。

**Comment by overtrue** [comment]
@pandao 加油！

**Comment by tangtang1251** [comment]
@overtrue 难道是makedown2.0

**Comment by overtrue** [comment]
@tangtang1251 不是啊

**Comment by pandao** [comment]
@overtrue @tangtang1251 最新的 `master` 已经修复这个问题了。

**Comment by overtrue** [comment]
@pandao 真迅速！:+1:

**Comment by pandao** [comment]
fixed @v1.4.4 .
