### ISSUE TITLE
图片文件名带@的会造成markdown解析成邮箱

### ISSUE THREAD

**Issue by overtrue** [pandao/editor.md#82]
`![](/editor.md/examples/php/../uploads/QQ20150427-1@2x.png)`

![image](https://cloud.githubusercontent.com/assets/1472352/7490218/0cfffefe-f411-11e4-9bfe-b4d342edcfe0.png)

![image](https://cloud.githubusercontent.com/assets/1472352/7490225/177ada70-f411-11e4-99b0-412d9af5c21f.png)

**Comment by pandao** [comment]
@overtrue 这个问题之前已经解决了，你可能是在看图片上传的示例 [http://www.ipandao.com/editor.md/examples/image-upload.html](http://www.ipandao.com/editor.md/examples/image-upload.html)，那个是我放在另一个网站上的，没同步更新，所以版本比较低，那个是 v1.3.0。

**Comment by overtrue** [comment]
OK
