### ISSUE TITLE
建议上传图片增加返回路径

### ISSUE THREAD

**Issue by overtrue** [pandao/editor.md#83]
现实中我们通常很少以文件原名存储文件，而是md5或者其它按时间创建目录后加随机名等不同的形式来处理上传图片，所以，建议在图片上传这里增加由服务端返回路径的方式来显示图片。
 
```       
{
      success : 0 | 1,   // 0表示上传失败，1表示上传成功
      message : "提示的信息，上传成功或上传失败及错误信息等。",
      url: '真实的URL',
      title: 可选，通常为文件原名
}
```

**Comment by pandao** [comment]
@overtrue 图片路径原本就是设计成服务器返回的，只是返回的 JSON 没有 `title` ，会考虑增加 `title`。

**Comment by overtrue** [comment]
@pandao 哦，我看例子里没说 :smile:

**Comment by pandao** [comment]
@overtrue 不好意思，检查了一下是示例没说清楚，稍后改正。
