### ISSUE TITLE
与Bootstrap好像不配合啊。

### ISSUE THREAD

**Issue by wolfan** [pandao/editor.md#84]
如果放在Bootstrap的模拟框中，watch : false, 打开后是无法关闭预览。
而且各种弹框也会位移，全屏也无法正常使用。
![image](http://dimg.vim-cn.com/3e/ca9e7e3fee9591bbb5949476184e8ceb2d718e.png)

**Comment by pandao** [comment]
@wolfan 我无法知道你的代码是怎么样的，所以请自己检查样式是否被覆盖、JS错误等等。

**Comment by wolfan** [comment]
我就是把 simple里的编辑框部分套在 http://v3.bootcss.com/javascript/#modals-sizes 这个大框里……
应该没问题吧……

**Comment by pandao** [comment]
@wolfan F12 审查元素检查一下。

**Comment by jimmykuu** [comment]
在 `shown.bs.modal` 事件里面初始化编辑框，可以保持样式正确。

具体如何用可以参考下， http://golangtc.com/t/55476b16421aa93720000003
