### ISSUE TITLE
代码块里面的[&times]被转义成[×]

### ISSUE THREAD

**Issue by hepeichun** [pandao/editor.md#840]
代码块里面的[&times]被转义成[×]

这理论上不应该存在
![image](https://user-images.githubusercontent.com/13855247/87430292-971c8e80-c617-11ea-892c-d51a1b90b0bb.png)
![image](https://user-images.githubusercontent.com/13855247/87430327-a3085080-c617-11ea-9cb0-835b92055fd4.png)

**Comment by WHFo** [comment]
存数据库之前对 &全部替换为&的实体字符即可解决即可解决。

**Comment by hepeichun** [comment]
> 存数据库之前对 &全部替换为&的实体字符即可解决即可解决。

谢谢
