### ISSUE TITLE
[建议]希望体验更加完善一下。

### ISSUE THREAD

**Issue by 9v-kz** [pandao/editor.md#86]
注重细节，能把编辑器更智能。
比如：从Toolbar或者用快键方式插入 标题`#` ，水平线`---`，有序(无序)列表等一系列元素方面作者没做相应判断。

这么说吧：
1. 插入水平线应该做一些位置判断，现在的编辑器从工具栏插入水平线的时候直接插入到正在写着的内容旁边，导致用鼠标放在前面重新换行。在这儿合理的方式是先判断位置，如果在段落里：插入时段落后面加个换行并插入。
2. 插入标题：同样是插入到内容旁边，合理的方式也是先判断位置，如果在段落里：插入到段落最前面。

有序无需列表之类的不一一说了。估计您也知道我的意思了。我觉得编辑器工具栏促进小白用户不知道Markdown格式的情况下也可以轻松的编写排版好看的内容。

**Comment by pandao** [comment]
@9v-kz 我知道你的意思，但真的无法做所谓的位置判断，毕竟还是不同于HTML可视化编辑器的，如果你了解 Editor.md 的原理或者说架构，你会明白我说的。
世面上也没有这么 “智能” 的 Markdown 编辑器，只能是当你要插入标题H1~H6或水平线时，自己下意识地先换行。
另外，不先学习一下 Markdown 语法就来用 Markdown 编辑器这不太合理，就好比开车不先学开车一样。

**Comment by 9v-kz** [comment]
@pandao 好吧。可能是我想的太简单了把。Codemirror 没有相应的函数吗？
```javascript
 hr : function() {
            var cm        = this.cm;
            var cursor    = cm.getCursor();
            var selection = cm.getSelection();

            cm.replaceSelection("------------");
        }
```
在这里像水平线这样的做了简单replace，是不是要判断一下CursorLine之类的之后做相应的插入。。。Codemirror的函数是不是不支持这样的操作？我是不熟悉。

**Comment by pandao** [comment]
@9v-kz 也不知道怎么跟你解释，CM 没有方法，也没有意义的。
