### ISSUE TITLE
在Markdown转HTML的显示页面，有些数学公式不能正常显示。

### ISSUE THREAD

**Issue by anby2015** [pandao/editor.md#87]
在用editormd.markdownToHTML时，如果 数学公式的内容有 "<" 或者 ">"符号时，数学公式显示不出来。
比如 : 公式是 $$x < y < Z $$,在控制台会报错："Error: KaTeX parse error: Unexpected character: '&' at position 2: x ̲'&'lt; y '&'lt; Z "
 公式是 $$x\leq y < z $$,在控制台会报错："Error: KaTeX parse error: Unexpected character: '&' at position 8: x\leq y ̲'&'lt; Z"
 公式是 $$x > y > Z $$,在控制台会报错："Error: KaTeX parse error: Unexpected character: '&' at position 2: x ̲ '&'gt; y '&'gt; Z ".

**Comment by pandao** [comment]
@anby2015 已标记，稍后修正。

**Comment by pandao** [comment]
@anby2015 已标记，稍后修正。

**Comment by anby2015** [comment]
谢谢。

**Comment by anby2015** [comment]
我找到解决这个问题的方法了。
修改editormd.markdownToHTML函数，在其调用katex.render()进行解析前，替换要的解析的字符串里的符号。把实体符号'&'lt; 替换成左尖括号，实体符号'&'gt;替换成右尖括号，这样数学公式就可以正常显示了。
具体修改代码：
把第3783行：
```javascript
katex.render(tex.html(), tex[0]);
```
修改为：
```javascript
var tex_html = tex.html();
tex_html = tex_html.replace(/&lt;/g, '<');
tex_html = tex_html.replace(/&gt;/g, '>');
katex.render(tex_html, tex[0]);
```

**Comment by pandao** [comment]
@anby2015 fixed @v1.4.5
