### ISSUE TITLE
想更改字号、字体、颜色之类的，是否支持CSS配置

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#88]
想更改字体、字号，还有颜色之类的，总之是一些宏观的东西。毕竟用的时候肯定要与网站整个风格一致。
是不是支持配置CSS，而不是在作者的CSS上修改，从而可以修改一些诸如字号、字体、颜色等样式。
看到了一个关于theme的配置，那个只是一些背景色之类的改变，并不能满足要求。
比如说，我想自己配置成这样：
![cmd markdown -](https://cloud.githubusercontent.com/assets/7576559/7652681/a3693590-fb41-11e4-8319-2053ca6b33ef.png)

**Comment by pandao** [comment]
@wakaryry 如果能了解 `Editor.md` 的源码，完全可以自定义。
因为用户的需求是各种各样的，Editor.md 也只能满足最基本的通用需求，所以更多个性化的需求则需要用户自己去自定义。
