### ISSUE TITLE
多个空的换行怎么弄？

### ISSUE THREAD

**Issue by HCenggel** [pandao/editor.md#889]
编辑器没有找到多个空行的语句

目前只能是这样
AAAAAAAAAAAAAAAA
 -- 空行
BBBBBBBBBBBBBBBBBB

但是并不能这样，也就是说不能在两段文字之间加很大的距离
AAAAAAAAAAAAAAAA
 -- 空行
 -- 空行
 -- 空行
 -- 空行
 -- 空行
BBBBBBBBBBBBBBBBBB

目前我们在md里面写&emsp;实现

能否加个多行空行的

**Comment by kohunglee** [comment]
在调用editormd的地方，加上
```
htmlDecode : "style,script,iframe,sub,sup,embed|onclick,title,onmouseover,onmouseout,style",
```
然后，可以在空的地方```<br/>```或者```&nbsp;```来代替空格，回车后就会形成空行
