### ISSUE TITLE
请问为什么我的TOC点击会刷新打开新的页面，而不会定位，求大佬！

### ISSUE THREAD

**Issue by Vino1016** [pandao/editor.md#893]
<img width="346" alt="iShot2020-12-26 00 23 33" src="https://user-images.githubusercontent.com/37614592/103138799-00e5ac00-4711-11eb-88e8-2495102590f8.png">

点击之后不会定位，反而会打开新的标签页刷新。
<img width="410" alt="iShot2020-12-26 00 23 44" src="https://user-images.githubusercontent.com/37614592/103138775-ca0f9600-4710-11eb-8025-f43596f0424c.png">
这是我的设置，应该是没错的。
<img width="539" alt="iShot2020-12-26 00 25 22" src="https://user-images.githubusercontent.com/37614592/103138778-da277580-4710-11eb-887a-142bdc28c458.png">

**Comment by leroy33** [comment]
你好，请问你是怎么解决的这个问题呀
