### ISSUE TITLE
chrome 87 版本 上传图片失败

### ISSUE THREAD

**Issue by tongjuhua** [pandao/editor.md#894]
报错如下
VM551:4 Uncaught SyntaxError: Unexpected token 下 in JSON at position 110
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.uploadIframe.onload (image-dialog.js:161)

**Comment by tongjuhua** [comment]
麻痹是迅雷插件个b再json后面追加了文字。

**Comment by ZaL0-0** [comment]
@tongjuhua 我没用迅雷也报了同样的错  麻烦问下你那边是怎么写的 方便截个图不
