### ISSUE TITLE
Rerender issues

### ISSUE THREAD

**Issue by zhouzhuojie** [pandao/editor.md#9]
Can you add a throttle function to your rerender event? Currently it renders every time we type something, it feels a lit bit lagged (especially when you keep pressing 'enter'). Some throttle function like once per 300ms would be easy to fix this.

Overall, it's an awesome project.

**Comment by pandao** [comment]
I didn't know you were in what circumstances feel slow? If it is too much on the content of the document, and the use of TeX, FlowChart and Sequence diagram, Renderer will has a delayed.It remains to be optimized.

**Comment by pandao** [comment]
I didn't know you were in what circumstances feel slow? If it is too much on the content of the document, and the use of TeX, FlowChart and Sequence diagram, Renderer will has a delayed.It remains to be optimized.

**Comment by pandao** [comment]
@zhouzhuojie Now, I think, you are right. The Editor.md lastst version will add delay mode. Thanks!
