### ISSUE TITLE
editormd移动端bug

### ISSUE THREAD

**Issue by gtxzsxxk** [pandao/editor.md#909]
我使用的是安卓的edge浏览器，在我的网页测试中，只要我在编辑器里键入一个字，就会将全文自动往下新增一行。现在移动端完全不能使用editormd编辑文本，这是一个很严重的bug。望修复，各位辛苦

**Comment by madeyoga** [comment]
#396

**Comment by mqingqing123** [comment]
这是Codemirror的问题，下载最新版的Codemirror5.6.1.0，然后找到codemirror.js和mode/markdown.js 覆盖 editormd的codemirror.min.js和 /lib/codemirror/mode/markdown  即可。
我自己更新了，也可以直接另存为这2个JS（version 5.6.1.0）
http://demo.dotnetcms.org/kbase/javascript/pandao-markdown/lib/codemirror/codemirror.min.js 
http://demo.dotnetcms.org/kbase/javascript/pandao-markdown/lib/codemirror/mode/markdown/markdown.js

**Comment by kohunglee** [comment]
不仅需要更新codemirror.min.js，它的css样式codemirror.min.css也要更新，否则会显示不正常。建议从codemirror官网官网下载最新版本codemirror-5.61.1，打开压缩包，将/codemirror-5.61.1/lib/目录下的这两个文件，名字中间加上min即codemirror.min.js和codemirror.min.css,，拷贝到 editormd的/lib/codemirror/下做个替换，然后就好了

**Comment by gtxzsxxk** [comment]
copied,感谢热心人士们的帮助
