### ISSUE TITLE
How to set the width to editor and preview

### ISSUE THREAD

**Issue by dineshck** [pandao/editor.md#922]
How to change default width of the editor width to 30% and preview to 70%.
I mean left side will have a default width of 30% and right side preview will have 70%.
Please reply at the earliest.

Thanks

**Comment by mqingqing123** [comment]
As it use codemirror css, so add codemirror css 
 
<style>
    .CodeMirror { width:30% !important }
    .editormd-preview{ width:70%  !important}
</style>

**Comment by dineshck** [comment]
> As it use codemirror css, so add codemirror css
> 
> <style> .CodeMirror { width:30% !important } .editormd-preview{ width:70% !important} </style>

It is perfectly okay, thanks a lot
