### ISSUE TITLE
获取不到textarea的值？？？ 这个是同步异步造成的吗？

### ISSUE THREAD

**Issue by sumiaowen** [pandao/editor.md#95]
$(function() {
        var editor = editormd("editormd", {
            path : "editor-md-master/lib/",
            width:'90%',
            height:'640',
            imageUpload    : true,
            imageFormats   : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "editor-md-master/examples/php/upload.php",
            saveHTMLToTextarea:true
        });
        $('#submit').click(function(){
            console.log(editor.getMarkdown())  //获取值正常
            console.log(editor.getHTML())  //获取不到值
            console.log(editor.getPreviewedHTML())  //正常
            return false;
        })

    });

**Comment by Weston-Liu** [comment]
我也遇到了此问题，不仅我的获取不到，Simple中的都获取不到。。。

**Comment by pandao** [comment]
@sumiaowen @Weston-Liu  fixed @v1.4.5
