### ISSUE TITLE
不知道为什么上传图片的请求没有载荷

### ISSUE THREAD

**Issue by Stapxs** [pandao/editor.md#956]
迷惑了好久后端怎么拿不到图片，好奇看了眼请求貌似根本就没有载荷发送了图片，不知道是为什么。

![image](https://user-images.githubusercontent.com/42486439/168456066-24de786a-99ae-4183-8f68-78336be7f892.png)

初始化代码：
~~~
window.parent.editor = editormd("editor", {
        path : "/editor/lib/",
        theme : "dark",
        previewTheme : "dark",
        editorTheme : 'pastel-on-dark',
        watch : false,
        saveHTMLToTextarea : true,
        imageUpload : true,
        imageFormats : ["jpg", "jpeg", "gif", "png"],
        imageUploadURL : "/api/article/img/upload"
    });
~~~

版本：`v1.5.0`

**Comment by suguer** [comment]
我也有这个问题,所以是有上传图片还是没有的呢

**Comment by Stapxs** [comment]
> 我也有这个问题,所以是有上传图片还是没有的呢

我看了下 HTML 结构图片是用最简单的表单提交 multipart/form-data 交上去的
理论上说上传是不会出问题的
![image](https://user-images.githubusercontent.com/42486439/168582334-3df71339-1b12-4fc1-b2b9-9dc5faac4116.png)

我折腾了半天是后端处理 multipart/form-data 提交的表单有问题所以我关掉了（x
