### ISSUE TITLE
解决Firefox下图片上传后返回值接收错误

### ISSUE THREAD

**Issue by jimmykuu** [pandao/editor.md#96]
plugins/image-dialog/image-dilaog.js 153行

Firefox 里面 `innerText` 无效，要通过 `textContent` 取值，因此改成这样就可以了：

    var json = uploadIframe.contentWindow.document.body.innerText;
    if (!json) {
        json = uploadIframe.contentWindow.document.body.textContent;
    }

**Comment by pandao** [comment]
@jimmykuu fixed @v1.4.5
