### ISSUE TITLE
建议添加选中文本的拖放功能

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#98]
个人觉得选中一个文本，然后将其拖动，再放到另一个位置是十分常用的一个功能。

**Comment by pandao** [comment]
@wakaryry 提议是很好，但是 CodeMirror 没有的功能，自己要实现可是不那么容易的，暂时就不考虑了。

**Comment by Ryongyon** [comment]
这个功能确实不好实现，而且话说明明就是复制、粘贴能搞定的事情，为了节省这点时间多些那么多代码觉得弊大于利
